"""Camera module — HTTP router + ustreamer supervisor.

The previous implementation kept a background thread with an OpenCV
``VideoCapture`` open on every active camera. The fragility of that
loop (Windows C++ exceptions on locked hardware, ``opencv-python``
wheels emitting SIGILL on mismatched ABIs, ``cv2.imencode`` paying a
numpy round-trip per frame) and the cost of supporting per-frame
``jpeg_quality`` / ``target_fps`` knobs pushed the streaming concern
out of the backend.

The camera module is now a thin layer on top of ``ustreamer`` — a
pure-C MJPEG/HTTP server that already powers every 3D-printer camera
panel on the planet (OctoPrint, Mainsail, Fluidd). Each detected
``/dev/videoN`` device gets its own ``ustreamer`` subprocess bound to
``http://127.0.0.1:{8080+index}/?action=stream``; the backend
``/stream`` endpoint is a 302 redirect to that URL.

Endpoints (mounted by the registry under ``/api/v1/modules/camera``):

* ``GET /devices`` — combination of detected USB devices (via
  ``/dev/video*`` + ``v4l2-ctl --list-devices``) plus the IP-camera
  URL configured in settings, so the Vue picker has one place to look.
* ``GET /stream`` — 302 redirect to the per-device ``ustreamer``
  URL, or a 503 with a plain-English ``message`` describing why the
  stream cannot be served (dependency missing, device absent,
  platform unsupported, etc.).
* ``GET /status`` — ``{running, active_id, ustreamer_url, message}``
  for the Settings panel's status row. ``message`` is empty when the
  stream is healthy and carries a single-line operator hint otherwise.
* ``GET /usb`` — kept URL-compatible with the legacy router so the
  frontend picker does not change; today it is the same shape as
  ``GET /devices`` minus the IP-camera row.

The ``/stream`` endpoint intentionally does not stream bytes itself.
Browsers fetching an ``<img src>`` follow 302 redirects transparently
without paying any CORS preflight, so the redirect-to-ustreamer
pattern works out of the box in dev (Vite proxies ``/api`` to 8000)
and in production (operator opens the SPA via the same hostname as
the backend).

Why no OpenCV / no Python capture? See
``.agent/context/LESSONS_LEARNED.md`` § 4.1 — the original
``opencv-python-headless`` import was the SIGILL trap that crashed
the FastAPI lifespan on misconfigured hosts, and ustreamer is faster,
lighter, and predictable. Do NOT reintroduce ``cv2`` into this
module; the supervisor owns the only process boundary the camera
needs.
"""
from __future__ import annotations

import asyncio
import logging
import os
import shutil
import subprocess
import sys
import threading
from datetime import datetime, timedelta, timezone
from typing import Dict, List, Optional
from urllib.parse import urlparse

from fastapi import APIRouter, HTTPException, Query, Request
from fastapi.responses import RedirectResponse

from .detection import USBDeviceInfo, detect_usb_cameras
from .settings import CameraSettings

logger = logging.getLogger("backend.modules.camera")


# ---------------------------------------------------------------------- #
# Module-level singletons                                                 #
# ---------------------------------------------------------------------- #


# The router is module-level so the registry can mount it; the
# supervisor is module-level so all endpoints share the same
# process table. ``CameraModule.on_load`` wires the settings store
# onto the supervisor via :func:`bind_settings_store`.
router = APIRouter(tags=["modules:camera"])

# ``UstreamerSupervisor`` is defined further down — the import order is
# (router, supervisor) first so the endpoints can reference the
# supervisor even though the class itself is declared below.
_supervisor: "UstreamerSupervisor"


# ---------------------------------------------------------------------- #
# Pydantic response models                                                #
# ---------------------------------------------------------------------- #


class USBDevicePayload:
    """Backward-compatible import shim — see ``USBDeviceInfo``.

    Removed: the old Pydantic-flavoured payload had an ``index`` field
    described as ``"OpenCV integer index"``. The detection layer no
    longer references OpenCV; the index is the V4L2 integer index.
    ``/usb`` continues to return the same JSON shape so the frontend
    picker is unchanged.
    """

    def __new__(cls, *, id: str, name: str, index: int) -> "USBDevicePayload":
        # The OpenAPI schema is generated by FastAPI from the
        # ``response_model=`` annotation on the endpoint, not from this
        # class. Returning the same dict shape the legacy endpoint
        # returned keeps the OpenAPI contract stable.
        return {"id": id, "name": name, "index": index}


class USBDevicesResponse:
    """``GET /usb`` response payload (kept URL-compatible)."""


class DevicePayload:
    """One row in the ``/devices`` response (USB + IP cameras)."""


class DevicesResponse:
    """``GET /devices`` response payload."""


class StreamStatusResponse:
    """``GET /status`` response payload.

    Attributes:
        running: True when the supervisor has a ustreamer child for
            the configured ``default_device_id`` and the child is
            alive.
        active_id: Identifier of the camera currently serving the
            next ``/stream`` request (``/dev/videoN`` path or HTTP
            URL). ``None`` when no id is configured.
        ustreamer_url: The full URL the next ``/stream`` request
            would redirect to, or ``None`` when no stream is
            available.
        message: Single-line operator hint describing why the
            stream cannot be served. Empty when ``running`` is
            ``True``.
    """

    running: bool
    active_id: Optional[str]
    ustreamer_url: Optional[str]
    message: str


# ---------------------------------------------------------------------- #
# UstreamerSupervisor                                                     #
# ---------------------------------------------------------------------- #


# Port allocation strategy: one ustreamer per detected device, starting
# at 8080 + index. The supervisor persists the actual port alongside
# the device id in its in-process map; the mapping is stable for the
# lifetime of the backend process. Operators that need to bookmark a
# stream URL can rely on the port staying put until the backend
# restarts.
_USTREAMER_BASE_PORT = 8080


class UstreamerSupervisor:
    """One ``ustreamer`` subprocess per ``/dev/videoN`` device.

    The supervisor owns:

    * the per-device subprocess table (``_procs``: id -> Popen);
    * the device → port mapping (``_ports``);
    * a per-device cooldown (``_cooldown_until``) so a freshly-failed
      device is not hammered by the frontend's exponential backoff;
    * the diagnostic ``message`` returned to the frontend via
      ``status()`` and the ``/stream`` 503 body.

    Thread-safety
    -------------
    Public methods (``spawn_or_reuse``, ``stop``, ``shutdown``,
    ``status``, ``read_default_device_id``, ``read_ip_camera_url``)
    take :attr:`_lock` so concurrent FastAPI threadpool tasks cannot
    tear a child down twice.

    Why not just a module-level capture?
    ------------------------------------
    The supervisor spawns one ``ustreamer`` per id the first time a
    client requests ``/stream?id=...``. The child stays alive until
    the operator switches cameras or the backend shuts down. Unlike
    the OpenCV-era design there is no per-frame loop on the Python
    side; the child owns the capture / encode cycle entirely.
    """

    # ustreamer flags we always pass. Resolution / framerate / encoder
    # quality are not user-tunable from the settings panel — they live
    # here as constants and would only move to settings if a future
    # ticket adds a "stream quality" selector.
    _USTREAMER_ARGS = (
        "-m",  # MJPEG output
        "JPEG",
        "-r", "640x480",  # resolution
        "-f", "30",  # framerate cap
        "--allow-origin", "*",  # CORS for browser <img> tags
    )

    def __init__(self) -> None:
        self._lock = threading.Lock()
        # id → ``subprocess.Popen`` handle.
        self._procs: Dict[str, "subprocess.Popen[bytes]"] = {}
        # id → assigned TCP port.
        self._ports: Dict[str, int] = {}
        # id → next-eligible ``datetime`` after which retries are
        # allowed. Mirrors the OpenCV-era cooldown so the frontend's
        # exponential backoff does not pile requests on a freshly-
        # crashed device.
        self._cooldown_until: Dict[str, datetime] = {}
        self._cooldown_seconds = 5.0
        self._settings_store = None  # late-bound by bind_settings

    # ------------------------------------------------------------------ #
    # Lifecycle                                                          #
    # ------------------------------------------------------------------ #

    def bind_settings(self, settings_store) -> None:
        """Attach the module's SettingsStore. Idempotent."""
        self._settings_store = settings_store

    def shutdown(self) -> None:
        """Terminate every spawned child. Idempotent."""
        with self._lock:
            for camera_id in list(self._procs.keys()):
                self._terminate_locked(camera_id)

    # ------------------------------------------------------------------ #
    # Settings passthrough                                                #
    # ------------------------------------------------------------------ #

    def _load_settings(self) -> CameraSettings:
        """Read the merged settings; fall back to defaults on error.

        Mirrors the legacy ``StreamManager.reload_config`` shape so a
        malformed PUT never crashes the streaming path.
        """
        try:
            if self._settings_store is None:
                return CameraSettings()
            payload = self._settings_store.read_all()
            return CameraSettings(**payload)
        except Exception as exc:  # noqa: BLE001
            logger.warning(
                "UstreamerSupervisor: invalid settings payload (%s); "
                "using defaults",
                exc,
            )
            return CameraSettings()

    def read_default_device_id(self) -> Optional[str]:
        """Return the configured ``default_device_id`` (or ``None``)."""
        value = getattr(self._load_settings(), "default_device_id", "")
        return value or None

    def read_ip_camera_url(self) -> Optional[str]:
        """Return the configured ``ip_camera_url`` (or ``None``)."""
        value = getattr(self._load_settings(), "ip_camera_url", "")
        return value or None

    # ------------------------------------------------------------------ #
    # Device discovery                                                   #
    # ------------------------------------------------------------------ #

    def known_device_ids(self) -> List[str]:
        """Return the ``/dev/video*`` paths the detection layer found.

        The supervisor treats ``known_device_ids`` as the authoritative
        list when an explicit ``/stream?id=...`` request asks for a
        device that was not enumerated. Anything outside this list
        still gets a fallback diagnostic but is treated as missing.
        """
        return [device.id for device in detect_usb_cameras()]

    # ------------------------------------------------------------------ #
    # Spawn / Stop                                                       #
    # ------------------------------------------------------------------ #

    def spawn_or_reuse(self, camera_id: str) -> Dict[str, str]:
        """Return ``{"id": ..., "url": ...}`` for ``camera_id``.

        Spawns the child if it is not already running. Raises
        :class:`RuntimeError` if the spawn fails — callers should
        translate that into an actionable HTTP error.
        """
        if not camera_id:
            raise RuntimeError("camera_id is required")

        with self._lock:
            cooldown_until = self._cooldown_until.get(camera_id)
            if cooldown_until is not None:
                now = datetime.now(timezone.utc)
                if now < cooldown_until:
                    remaining = (cooldown_until - now).total_seconds()
                    raise RuntimeError(
                        f"Camera {camera_id!r} is in cooldown "
                        f"({remaining:.1f}s remaining)"
                    )
                del self._cooldown_until[camera_id]

            proc = self._procs.get(camera_id)
            if proc is not None and proc.poll() is None:
                # Still alive — reuse.
                port = self._ports[camera_id]
                return {"id": camera_id, "url": self._stream_url(port)}

            # Either no child or it has exited. (Re)spawn.
            try:
                port = self._ports[camera_id]
            except KeyError:
                port = self._allocate_port(camera_id)
                self._ports[camera_id] = port

            proc = self._spawn_locked(camera_id, port)
            self._procs[camera_id] = proc
            logger.info(
                "UstreamerSupervisor: spawned ustreamer id=%s port=%d (pid=%d)",
                camera_id,
                port,
                proc.pid,
            )
            return {"id": camera_id, "url": self._stream_url(port)}

    def stop(self, camera_id: str) -> None:
        """Terminate the child for ``camera_id`` if any. Idempotent."""
        with self._lock:
            self._terminate_locked(camera_id)

    # ------------------------------------------------------------------ #
    # Status / diagnostic                                                 #
    # ------------------------------------------------------------------ #

    def status(self) -> Dict[str, object]:
        """Return the JSON payload for ``GET /status``.

        Always returns ``running`` as a boolean; ``message`` is empty
        when ``running`` is True and otherwise carries a single-line
        operator hint explaining what is missing.
        """
        with self._lock:
            active_id = self.read_default_device_id()

            # Pre-flight diagnostic checks (cheap; no subprocess I/O).
            message = self._diagnostic_message_locked(active_id)
            if message:
                return {
                    "running": False,
                    "active_id": active_id,
                    "ustreamer_url": None,
                    "message": message,
                }

            # No id configured — operator has not picked a device yet.
            if not active_id:
                return {
                    "running": False,
                    "active_id": None,
                    "ustreamer_url": None,
                    "message": "",
                }

            proc = self._procs.get(active_id)
            if proc is None or proc.poll() is not None:
                # Child not running or has exited. Operator needs to
                # know whether the problem is ustreamer itself or
                # something downstream (port already bound, device
                # busy, etc.).
                if proc is not None:
                    code = proc.returncode
                    self._cooldown_until[active_id] = (
                        datetime.now(timezone.utc)
                        + timedelta(seconds=self._cooldown_seconds)
                    )
                    self._procs.pop(active_id, None)
                    return {
                        "running": False,
                        "active_id": active_id,
                        "ustreamer_url": None,
                        "message": (
                            f"ustreamer exited unexpectedly "
                            f"(code {code}). Check the backend logs "
                            f"for details."
                        ),
                    }
                # No child has been spawned yet — tell the operator to
                # click the camera (which fires the first /stream).
                return {
                    "running": False,
                    "active_id": active_id,
                    "ustreamer_url": None,
                    "message": "",
                }

            port = self._ports.get(active_id)
            return {
                "running": True,
                "active_id": active_id,
                "ustreamer_url": self._stream_url(port) if port else None,
                "message": "",
            }

    def _diagnostic_message_locked(self, camera_id: Optional[str]) -> str:
        """Return a one-line operator hint, or ``""`` if everything is fine.

        Caller must hold :attr:`_lock`. Resolution order:

        1. Non-Linux platform → dependency message (ustreamer is Linux-only).
        2. ``ustreamer`` binary missing on PATH.
        3. ``camera_id`` provided but not present in ``/dev/video*``.
        4. No devices and no IP camera configured.
        """
        if not sys.platform.startswith("linux"):
            return (
                "The camera module requires Linux; ustreamer does not "
                "run on this platform."
            )

        if shutil.which("ustreamer") is None:
            return (
                "ustreamer is not installed on this host. Run "
                "'sudo apt install ustreamer' on the LinuxCNC controller."
            )

        known = self.known_device_ids()
        if camera_id and not camera_id.startswith(("http://", "https://", "rtsp://")):
            if camera_id not in known:
                return (
                    f"Camera {camera_id} is not present. Reconnect the "
                    f"camera or pick another device."
                )

        if not known and not self.read_ip_camera_url():
            return (
                "No USB cameras detected and no IP camera configured. "
                "Plug in a camera or save an IP camera URL."
            )

        return ""

    # ------------------------------------------------------------------ #
    # Subprocess plumbing                                                 #
    # ------------------------------------------------------------------ #

    def _allocate_port(self, camera_id: str) -> int:
        """Pick a TCP port for ``camera_id``.

        Strategy: index by enumeration order, so ``/dev/video0`` →
        8080, ``/dev/video1`` → 8081, … The operator can therefore
        bookmark a single camera and have the URL stay stable across
        restarts as long as the device order is preserved.
        """
        known = self.known_device_ids()
        try:
            idx = known.index(camera_id)
        except ValueError:
            # Unknown id — fall back to hash-derived port. Rare path;
            # the operator must explicitly request an unknown id.
            idx = abs(hash(camera_id)) % 1000
        return _USTREAMER_BASE_PORT + idx

    def _stream_url(self, port: int) -> str:
        """Build the URL the frontend ``<img>`` follows."""
        return f"http://127.0.0.1:{port}/?action=stream"

    def _spawn_locked(
        self, camera_id: str, port: int
    ) -> "subprocess.Popen[bytes]":
        """Spawn ``ustreamer -d <id> -p <port> ...``. Caller holds lock."""
        # ``camera_id`` may be an HTTP/RTSP URL (the IP-camera
        # passthrough). ustreamer cannot consume those directly; the
        # operator is expected to have set the URL only as a logical
        # marker and rely on the IP-camera entry showing up in the
        # picker. The supervisor still allocates a port so the URL
        # field has a stable value to display, but the child is not
        # spawned — the frontend surfaces the URL as a non-streamable
        # historical row.
        if camera_id.startswith(("http://", "https://", "rtsp://")):
            raise RuntimeError(
                f"Camera source {camera_id!r} is an HTTP/RTSP URL — "
                "ustreamer does not consume those. Use a local "
                "/dev/videoN device or terminate the IP-camera URL "
                "in the Settings panel."
            )

        args = [
            "ustreamer",
            "-d", camera_id,
            "-p", str(port),
            *self._USTREAMER_ARGS,
        ]
        try:
            return subprocess.Popen(
                args,
                stdout=subprocess.DEVNULL,
                stderr=subprocess.PIPE,
                # Detach so ustreamer does not block the Python loop
                # if its stderr pipe fills up.
                start_new_session=True,
            )
        except FileNotFoundError as exc:
            self._cooldown_until[camera_id] = (
                datetime.now(timezone.utc)
                + timedelta(seconds=self._cooldown_seconds)
            )
            raise RuntimeError(
                "ustreamer is not installed on this host. Run "
                "'sudo apt install ustreamer' on the LinuxCNC controller."
            ) from exc
        except Exception as exc:  # noqa: BLE001 - spawn failure modes vary
            self._cooldown_until[camera_id] = (
                datetime.now(timezone.utc)
                + timedelta(seconds=self._cooldown_seconds)
            )
            raise RuntimeError(
                f"Failed to spawn ustreamer for {camera_id!r}: {exc}"
            ) from exc

    def _terminate_locked(self, camera_id: str) -> None:
        """Terminate ``camera_id``'s child. Caller holds lock."""
        proc = self._procs.pop(camera_id, None)
        if proc is None:
            return
        if proc.poll() is None:
            try:
                proc.terminate()
                try:
                    proc.wait(timeout=2.0)
                except Exception:  # noqa: BLE001 - wait timeout path
                    proc.kill()
                    try:
                        proc.wait(timeout=1.0)
                    except Exception:  # noqa: BLE001
                        pass
            except Exception as exc:  # noqa: BLE001 - best-effort cleanup
                logger.debug(
                    "UstreamerSupervisor: terminate raised %s", exc
                )
        self._cooldown_until.pop(camera_id, None)
        logger.info(
            "UstreamerSupervisor: terminated ustreamer id=%s", camera_id
        )


# ---------------------------------------------------------------------- #
# Endpoints                                                               #
# ---------------------------------------------------------------------- #


def _safe_host(url: str) -> str:
    """Return a short, display-safe host portion of a URL."""
    try:
        host = urlparse(url).hostname or url
    except Exception:  # noqa: BLE001
        return url[:48]
    return host[:48] if host else url[:48]


@router.get(
    "/usb",
    summary="Detect attached USB cameras",
    description=(
        "Scan ``/dev/video*`` and return one row per device. ``name`` "
        "is the human-readable card string from "
        "``v4l2-ctl --list-devices`` when available; a synthetic "
        "fallback is used otherwise. The endpoint is URL-compatible "
        "with the legacy OpenCV-era router."
    ),
    operation_id="detectUsbCameras",
)
def detect_usb() -> Dict[str, object]:
    devices = detect_usb_cameras()
    return {
        "devices": [
            {"id": d.id, "name": d.name, "index": d.index} for d in devices
        ],
        "platform": sys.platform,
    }


@router.get(
    "/devices",
    summary="List all selectable cameras",
    description=(
        "Combination of the attached USB cameras and any IP-camera "
        "URL configured in the module settings. The ``source`` field "
        "distinguishes ``usb`` rows from ``ip`` rows."
    ),
    operation_id="listCameraDevices",
)
def list_devices() -> Dict[str, object]:
    out: List[Dict[str, str]] = [
        {"id": d.id, "name": d.name, "source": "usb"}
        for d in detect_usb_cameras()
    ]
    # IP camera passthrough: read the optional URL from settings.
    ip_url = _supervisor.read_ip_camera_url()
    if ip_url:
        out.append(
            {
                "id": ip_url,
                "name": f"IP Camera ({_safe_host(ip_url)})",
                "source": "ip",
            }
        )
    return {"devices": out}


@router.get(
    "/stream",
    summary="Get Live MJPEG Stream",
    description=(
        "Returns a 302 redirect to the per-device ``ustreamer`` MJPEG "
        "URL (``http://127.0.0.1:{port}/?action=stream``). Without "
        "query parameters the configured ``default_device_id`` is "
        "used; empty on first boot results in 503. When the stream "
        "cannot be served for any reason (dependency missing, device "
        "absent, platform unsupported, child crashed) the response "
        "is a 503 whose ``detail`` is a single-line operator hint."
    ),
    operation_id="streamCamera",
)
def camera_stream(
    id: Optional[str] = Query(
        default=None,
        description=(
            "Camera identifier (``/dev/videoN`` path or HTTP/RTSP URL). "
            "Defaults to the configured ``default_device_id``."
        ),
    ),
) -> RedirectResponse:
    camera_id = id or _supervisor.read_default_device_id()
    if not camera_id:
        raise HTTPException(
            status_code=503,
            detail=(
                "No camera selected. Pick a device in the Camera "
                "Settings panel, then request /stream?id=<device_id>."
            ),
        )
    try:
        info = _supervisor.spawn_or_reuse(camera_id)
    except RuntimeError as exc:
        raise HTTPException(status_code=503, detail=str(exc)) from exc
    return RedirectResponse(url=info["url"], status_code=302)


@router.get(
    "/status",
    summary="Get Supervisor Status",
    description=(
        "Returns ``{running, active_id, ustreamer_url, message}``. "
        "``running`` is true when the supervisor has a live "
        "``ustreamer`` child for the configured default device. "
        "``message`` is a single-line operator hint (empty when the "
        "stream is healthy) that distinguishes 'dependency missing' "
        "from 'device unplugged' from 'platform unsupported'."
    ),
    operation_id="getCameraStatus",
)
def camera_status() -> Dict[str, object]:
    return _supervisor.status()


# ---------------------------------------------------------------------- #
# Late binding                                                            #
# ---------------------------------------------------------------------- #

# Instantiate the singleton *after* :class:`UstreamerSupervisor` is
# declared so the class body is visible at module-load time.
_supervisor = UstreamerSupervisor()


def bind_settings_store(settings_store) -> None:
    """Attach a SettingsStore to the module-level supervisor.

    Called from :meth:`CameraModule.on_load` once the registry has
    built the per-module :class:`SettingsStore`. Idempotent: calling
    twice with the same store is a no-op.
    """
    _supervisor.bind_settings(settings_store)


def stop_manager() -> None:
    """Tear the supervisor down for ``on_unload``.

    Terminates every spawned child. Idempotent.
    """
    _supervisor.shutdown()


__all__ = [
    "UstreamerSupervisor",
    "USBDeviceInfo",
    "bind_settings_store",
    "router",
    "stop_manager",
]
