"""End-to-end compile, checked against a real, working machine.

`machine_config/example/PrintNC-WEBGUI/Machine.hal` is a hand-written,
functional class-A (parport) config — not generated by this compiler,
but a real PrintNC running it. This fixture mirrors its exact joint
layout, pin assignments and invert flags (read directly off that file)
as `hardware.json`, compiles it, and checks the output is
*structurally* equivalent: same components loaded, same `addf` thread
order, same net graph shape, same invert/reset flags — not a byte-for-
byte text diff, since this compiler's internal signal names
(`stepper_x-step`) don't have to match the hand-written ones (`xstep`).

Facts asserted here are quoted from that file, not invented:

  * joint 0 = X (step pin-08, dir pin-09 inverted)
  * joint 1 = Y (step pin-02, dir pin-03 inverted)
  * joint 2 = Y2 (step pin-04, dir pin-05 inverted)
  * joint 3 = Z (step pin-06, dir pin-07, NOT inverted)
  * X and Z share one endstop, "home-xz", on pin-13 (inverted: `-in-not`)
  * Y has its own endstop on pin-12; Y2 on pin-11 (neither inverted)
  * no joint has an enable pin wired to a physical output at all
    (this board enables steppers via a hardware jumper) — a real
    machine the compiler must not invent a pin for.
"""

from __future__ import annotations

import re
from pathlib import Path
from typing import Any

import pytest

from services.halcompiler import compile_machine_hal, validate_machine
from services.halcompiler.assembler import HalAssembler

REPO_ROOT = Path(__file__).resolve().parents[3]
REFERENCE_HAL = REPO_ROOT / "machine_config" / "example" / "PrintNC-WEBGUI" / "Machine.hal"

PAYLOAD: dict[str, Any] = {
    "version": "2.2",
    "machine": "printnc_reference",
    "source": "test",
    "kinematics": "cartesian",
    "hal_type": "parport",
    "mcus": [
        {
            "id": "mcu",
            "connection": "parallelport",
            "parameters": {"address": "0", "direction": "out", "reset_time": 2500},
        }
    ],
    "axes": [
        {"id": "x", "joint_numbers": [0], "endstop": "endstop_xz"},
        {"id": "y", "joint_numbers": [1], "endstop": "endstop_y"},
        {"id": "y2", "joint_numbers": [2], "endstop": "endstop_y2"},
        {"id": "z", "joint_numbers": [3], "endstop": "endstop_xz"},
    ],
    "joints": [
        {"id": "stepper_x", "joint_number": 0, "step_pin": "mcu:08", "dir_pin": "mcu:!09"},
        {"id": "stepper_y", "joint_number": 1, "step_pin": "mcu:02", "dir_pin": "mcu:!03"},
        {"id": "stepper_y2", "joint_number": 2, "step_pin": "mcu:04", "dir_pin": "mcu:!05"},
        {"id": "stepper_z", "joint_number": 3, "step_pin": "mcu:06", "dir_pin": "mcu:07"},
    ],
    "drivers": [],
    "fans": [],
    "temperature_sensors": [],
    "tools": [],
    "endstops": [
        {"id": "endstop_xz", "pin": "mcu:!13"},
        {"id": "endstop_y", "pin": "mcu:12"},
        {"id": "endstop_y2", "pin": "mcu:11"},
    ],
}


@pytest.fixture()
def fragment():
    return HalAssembler(PAYLOAD).assemble()


def test_reference_machine_hal_exists():
    """If this moved, every fact quoted in this file's docstring needs re-checking."""
    assert REFERENCE_HAL.exists(), f"reference machine missing: {REFERENCE_HAL}"


def test_fixture_validates_clean():
    assert validate_machine(PAYLOAD) == []


def test_component_set_matches_the_reference_machine():
    """Same realtime components — no more, no fewer."""
    fragment = HalAssembler(PAYLOAD).assemble()
    reference = REFERENCE_HAL.read_text(encoding="utf-8")

    for loadrt_component in ("KINEMATICS", "EMCMOT", "stepgen", "hal_parport"):
        assert any(loadrt_component in line for line in fragment.loadrt), loadrt_component
        assert loadrt_component in reference, f"test fixture drifted from {loadrt_component}"


def test_addf_thread_assignment_and_order_match(fragment):
    """The functional invariant: read -> make-pulses -> write -> reset."""
    base = [a.func for a in sorted(
        (a for a in fragment.addf if a.thread == "base-thread"), key=lambda a: a.order
    )]
    assert base == [
        "parport.0.read",
        "stepgen.make-pulses",
        "parport.0.write",
        "parport.0.reset",
    ]

    servo = [a.func for a in sorted(
        (a for a in fragment.addf if a.thread == "servo-thread"), key=lambda a: a.order
    )]
    assert servo == [
        "stepgen.capture-position",
        "motion-command-handler",
        "motion-controller",
        "stepgen.update-freq",
    ]


@pytest.mark.parametrize(
    "pin,expected_invert",
    [("08", "0"), ("09", "1"), ("02", "0"), ("03", "1"), ("04", "0"), ("05", "1"), ("06", "0"), ("07", "0")],
)
def test_invert_flags_match_the_reference_machine(fragment, pin, expected_invert):
    line = f"setp parport.0.pin-{pin}-out-invert {expected_invert}"
    assert line in fragment.setp, f"missing or wrong invert for pin {pin}: {fragment.setp}"


def test_only_step_pins_get_the_reset_flag(fragment):
    reset_pins = {re.search(r"pin-(\d+)-out-reset", s).group(1) for s in fragment.setp if "-out-reset" in s}
    assert reset_pins == {"08", "02", "04", "06"}  # the four step pins, never dir


def test_shared_and_independent_endstops_route_correctly(fragment):
    # X and Z: one shared, inverted switch.
    assert "net endstop_xz-sw <= parport.0.pin-13-in-not" in fragment.nets
    assert "net endstop_xz-sw => joint.0.home-sw-in" in fragment.nets
    assert "net endstop_xz-sw => joint.3.home-sw-in" in fragment.nets
    assert sum(1 for n in fragment.nets if "pin-13-in" in n) == 1  # not routed twice

    # Y and Y2: independent, non-inverted switches.
    assert "net endstop_y-sw <= parport.0.pin-12-in" in fragment.nets
    assert "net endstop_y2-sw <= parport.0.pin-11-in" in fragment.nets


def test_no_enable_pin_is_invented(fragment):
    """This board enables steppers via a hardware jumper — the reference
    file has no `pin-NN-out` for any `*enable*` signal, and the
    compiler must not invent one just because the field exists on the
    joint model."""
    assert not any("enable" in n and "parport" in n for n in fragment.nets)
    assert all("enable" not in s for s in fragment.setp if "parport" in s)


def test_full_render_is_well_formed_hal_text():
    text = compile_machine_hal(PAYLOAD)
    assert text.count("loadrt hal_parport") == 1
    assert "\n\n" in text  # sections are blank-line separated
    lines = [l for l in text.splitlines() if l.strip()]
    assert all(
        l.startswith(("loadrt ", "addf ", "setp ", "net ", "#")) for l in lines
    ), [l for l in lines if not l.startswith(("loadrt ", "addf ", "setp ", "net ", "#"))]
