# Basic LinuxCNC config for testing of Remora firmware

[EMC]
MACHINE = Remora-XY
DEBUG = 5
VERSION = 1.1

[DISPLAY]
DISPLAY = axis
USER_COMMAND_FILE = usercommand_regularmac_800.py
EDITOR = gedit
POSITION_OFFSET = RELATIVE
POSITION_FEEDBACK = ACTUAL
ARCDIVISION = 64
GRIDS = 10mm 20mm 50mm 100mm
MAX_FEED_OVERRIDE = 1.2
DEFAULT_LINEAR_VELOCITY = 5.00
MIN_LINEAR_VELOCITY = 0
MAX_LINEAR_VELOCITY = 10.00
DEFAULT_ANGULAR_VELOCITY = 36.00
MIN_ANGULAR_VELOCITY = 0
MAX_ANGULAR_VELOCITY = 45.00
INTRO_GRAPHIC = linuxcnc.gif
INTRO_TIME = 5
PROGRAM_PREFIX = ~/linuxcnc/nc_files
INCREMENTS = 50mm 10mm 5mm 1mm .5mm .1mm .05mm .01mm

[KINS]
JOINTS = 4
KINEMATICS = trivkins coordinates=X Y Z A

[FILTER]
PROGRAM_EXTENSION = .py Python Script
py = python

[TASK]
TASK = milltask
CYCLE_TIME = 0.010

[RS274NGC]
PARAMETER_FILE = linuxcnc.var

[EMCMOT]
EMCMOT = motmod
COMM_TIMEOUT = 1.0
COMM_WAIT = 0.010
BASE_PERIOD = 0
SERVO_PERIOD = 1000000

[HAL]
HALFILE = remora-xyz.hal
POSTGUI_HALFILE = postgui_call_list.hal

[TRAJ]
COORDINATES =  X Y Z A
LINEAR_UNITS = mm
ANGULAR_UNITS = degree
CYCLE_TIME = 0.010
DEFAULT_LINEAR_VELOCITY = 50.00
MAX_LINEAR_VELOCITY = 300
NO_FORCE_HOMING = 1

[AXIS_X]
MAX_VELOCITY = 300
MAX_ACCELERATION = 3000
MIN_LIMIT = 0
MAX_LIMIT = 200


[JOINT_0]
TYPE = LINEAR
HOME = 0
MIN_LIMIT = 0
MAX_LIMIT = 200
MAX_VELOCITY = 300
MAX_ACCELERATION = 3000
STEPGEN_MAXACCEL = 3300
SCALE = 80
FERROR = 2
MIN_FERROR = 1
HOME_OFFSET = 0
HOME_SEARCH_VEL = 10
HOME_LATCH_VEL = 10
HOME_SEQUENCE = 0

[AXIS_Y]
MAX_VELOCITY = 300
MAX_ACCELERATION = 3000
MIN_LIMIT = 0
MAX_LIMIT = 200


[JOINT_1]
TYPE = LINEAR
HOME = 0
MIN_LIMIT = 0
MAX_LIMIT = 200
MAX_VELOCITY = 300
MAX_ACCELERATION = 3000
STEPGEN_MAXACCEL = 3300
SCALE = 80
FERROR = 9
MIN_FERROR = 5
HOME_OFFSET = 0
HOME_SEARCH_VEL = 10
HOME_LATCH_VEL = 10
HOME_SEQUENCE = 0

[AXIS_Z]
MAX_VELOCITY = 300
MAX_ACCELERATION = 3000
MIN_LIMIT = 0
MAX_LIMIT = 200
OFFSET_AV_RATIO = 0.2

[JOINT_2]
TYPE = LINEAR
HOME = 0
MIN_LIMIT = 0
MAX_LIMIT = 200
MAX_VELOCITY = 300
MAX_ACCELERATION = 3000
STEPGEN_MAXACCEL = 3300
SCALE = 400
FERROR = 2
MIN_FERROR = 1
HOME_OFFSET = 0
HOME_SEARCH_VEL = 10
HOME_LATCH_VEL = 10
HOME_SEQUENCE = 0

[AXIS_A]
MAX_VELOCITY = 0
MAX_ACCELERATION = 0
MIN_LIMIT = 0
MAX_LIMIT = 0


[JOINT_0]
TYPE = LINEAR
HOME = 0
MIN_LIMIT = 0
MAX_LIMIT = 0
MAX_VELOCITY = 300
MAX_ACCELERATION = 3000
STEPGEN_MAXACCEL = 3300
SCALE = 95.5224
FERROR = 2
MIN_FERROR = 1
HOME_OFFSET = 0
HOME_SEARCH_VEL = 10
HOME_LATCH_VEL = 10
HOME_SEQUENCE = 0


[EMCIO]
EMCIO = io
CYCLE_TIME = 0.100
TOOL_TABLE = tool.tbl

# Ext0
[EXT0]
PID_PONM	= 1
PID_DIR		= 0
PID_KP		= 22.2
PID_KI		= 1.08
PID_KD		= 114
PID_SPMIN	= 0.0
PID_SPMAX	= 250
PID_CVMIN	= 0.0
PID_CVMAX	= 100.0


# Bed
[BED]
PID_PONM	= 1
PID_DIR		= 0
PID_KP		= 21.5
PID_KI		= 1
PID_KD		= 0
PID_SPMIN	= 0.0
PID_SPMAX	= 80
PID_CVMIN	= 0.0
PID_CVMAX	= 100.0

