"""Render LinuxCNC ``.hal`` files from :class:`Axis` / :class:`Joint` models.

The HAL file wires LinuxCNC's motion controller to the stepgen
channels exposed by the hardware. Two output modes are supported:

* ``remora`` — uses ``remora.stepgen.NN`` channels exposed by the
  Remora firmware. Pin assignments (``step_pin``, ``dir_pin``,
  ``enable_pin``) live in the Remora firmware config
  (``boardConfig.h``), not in the HAL file — the HAL file only
  wires the signals. The pins are included as comments for
  documentation.
* ``parallel`` — uses standard ``stepgen.N`` channels with
  explicit timing parameters (``steplen``, ``stepspace``,
  ``dirhold``, ``dirsetup``). This is the mode for parallel-port
  or Mesa-card setups.

The mode is selected via the ``hal_type`` key in the Klipper
``[mcu]`` section (default: ``remora``).

The renderer is deliberately template-based: the static skeleton
of a joint block lives as a multi-line string so operators can
hand-edit a familiar LinuxCNC file and the diff against the
generated output stays legible.

The dynamic section (one joint block per joint) is built by a
**Builder pattern**: the template walks the pre-resolved
:class:`list` of :class:`Axis` objects and emits one block per
joint. No 1:1 axis-to-joint assumption is hardcoded.
"""

from __future__ import annotations

import logging
from typing import Mapping

from ..models import Axis, IniConfig, Joint

logger = logging.getLogger("backend.modules.machineconfig.compilers.hal_generator")


# --------------------------------------------------------------------- #
# Static templates                                                       #
# --------------------------------------------------------------------- #

REMORA_HAL_HEADER_TEMPLATE = """\
# machine.hal
# Generated by KlipperToLinuxCNCCompiler (hal_type=remora)
# DO NOT EDIT — re-run the compiler to regenerate.

loadrt remora-xyz chip_type=STM32F429

loadrt thread names=base-thread,servo-thread period1=1000000 period2=1000000

addf remora.read                 servo-thread
addf motion-command-handler      servo-thread
addf motion-controller           servo-thread
addf remora.update-freq          servo-thread
addf remora.write                servo-thread

{joints_block}

net machine-is-on => {enable_signals}
"""

REMORA_JOINT_TEMPLATE = """\
# --- {axis_letter} axis (Joint {joint_number}) ---
# Pins: step={step_pin}, dir={dir_pin}, enable={enable_pin}
net {axis_letter_lower}pos-cmd  joint.{joint_number}.motor-pos-cmd  => remora.stepgen.{joint_number_padded}.position-cmd
net {axis_letter_lower}pos-fb   remora.stepgen.{joint_number_padded}.position-fb => joint.{joint_number}.motor-pos-fb
net {axis_letter_lower}enable   joint.{joint_number}.amp-enable-out  => remora.stepgen.{joint_number_padded}.enable
setp remora.stepgen.{joint_number_padded}.position-scale {scale}
"""

PARALLEL_HAL_HEADER_TEMPLATE = """\
# machine.hal
# Generated by KlipperToLinuxCNCCompiler (hal_type=parallel)
# DO NOT EDIT — re-run the compiler to regenerate.

loadrt stepgen step_type=0,0,0

loadrt thread names=base-thread,servo-thread period1=1000000 period2=1000000

addf stepgen.make-pulses base-thread
addf motion-command-handler servo-thread
addf motion-controller servo-thread
addf stepgen.capture-position servo-thread
addf stepgen.update-freq servo-thread

{joints_block}

net machine-is-on => {enable_signals}
"""

PARALLEL_JOINT_TEMPLATE = """\
# --- {axis_letter} axis (Joint {joint_number}) ---
# Pins: step={step_pin}, dir={dir_pin}, enable={enable_pin}
net {axis_letter_lower}pos-cmd  joint.{joint_number}.motor-pos-cmd  => stepgen.{joint_number}.position-cmd
net {axis_letter_lower}pos-fb   stepgen.{joint_number}.position-fb => joint.{joint_number}.motor-pos-fb
net {axis_letter_lower}enable   joint.{joint_number}.amp-enable-out  => stepgen.{joint_number}.enable
setp stepgen.{joint_number}.position-scale {scale}
setp stepgen.{joint_number}.steplen 1
setp stepgen.{joint_number}.stepspace 0
setp stepgen.{joint_number}.dirhold 35000
setp stepgen.{joint_number}.dirsetup 35000
setp stepgen.{joint_number}.maxaccel {maxaccel}
"""


# --------------------------------------------------------------------- #
# Builder                                                                #
# --------------------------------------------------------------------- #


class HalGenerator:
    """Render an :class:`IniConfig` into a LinuxCNC HAL string.

    The :meth:`render` method is the single public entry point; the
    builders below it are split so the dynamic section can grow new
    joint types (rotational, kinematic-switch) without touching the
    static header.

    Parameters
    ----------
    hal_type:
        ``"remora"`` (default) or ``"parallel"``. Selects the
        stepgen channel naming and whether timing parameters are
        emitted.
    """

    def __init__(self, hal_type: str = "remora") -> None:
        if hal_type not in {"remora", "parallel"}:
            raise ValueError(
                f"Unsupported hal_type '{hal_type}'; expected 'remora' or 'parallel'"
            )
        self.hal_type = hal_type

    def render(self, config: IniConfig) -> str:
        """Render the full HAL from an :class:`IniConfig`."""

        joints_block = self._build_joints_block(config.axes)
        enable_signals = self._build_enable_signals(config.axes)

        if self.hal_type == "parallel":
            header = PARALLEL_HAL_HEADER_TEMPLATE
        else:
            header = REMORA_HAL_HEADER_TEMPLATE

        return header.format(
            joints_block=joints_block,
            enable_signals=enable_signals,
        )

    # ----- Builders ----------------------------------------------- #

    def _build_joints_block(self, axes: list[Axis]) -> str:
        """Render one joint block per joint across all axes.

        The output keeps the canonical axis order so the resulting
        HAL is stable across runs.
        """
        chunks: list[str] = []
        for axis in axes:
            for joint in axis.joints:
                chunks.append(self._render_joint(joint))
        return "\n".join(chunks)

    def _render_joint(self, joint: Joint) -> str:
        """Render a single joint block."""
        if self.hal_type == "parallel":
            return PARALLEL_JOINT_TEMPLATE.format(
                axis_letter=joint.axis_letter,
                axis_letter_lower=joint.axis_letter.lower(),
                joint_number=joint.joint_number,
                step_pin=joint.step_pin or "N/A",
                dir_pin=joint.dir_pin or "N/A",
                enable_pin=joint.enable_pin or "N/A",
                scale=self._fmt(joint.scale),
                maxaccel=self._fmt(joint.stepgen_maxaccel),
            )
        return REMORA_JOINT_TEMPLATE.format(
            axis_letter=joint.axis_letter,
            axis_letter_lower=joint.axis_letter.lower(),
            joint_number=joint.joint_number,
            joint_number_padded=f"{joint.joint_number:02d}",
            step_pin=joint.step_pin or "N/A",
            dir_pin=joint.dir_pin or "N/A",
            enable_pin=joint.enable_pin or "N/A",
            scale=self._fmt(joint.scale),
        )

    def _build_enable_signals(self, axes: list[Axis]) -> str:
        """Build the ``net machine-is-on => ...`` signal list."""
        signals: list[str] = []
        for axis in axes:
            for joint in axis.joints:
                if self.hal_type == "parallel":
                    signals.append(f"stepgen.{joint.joint_number}.enable")
                else:
                    signals.append(f"remora.stepgen.{joint.joint_number:02d}.enable")
        return " ".join(signals)

    # ----- Helpers ------------------------------------------------ #

    @staticmethod
    def _fmt(value: float | int) -> str:
        """Format a numeric value, dropping trailing ``.0`` on integers."""

        if isinstance(value, bool):
            return str(value)
        if isinstance(value, int):
            return str(value)
        if isinstance(value, float):
            if value.is_integer():
                return str(int(value))
            return f"{value:.4f}".rstrip("0").rstrip(".")
        return str(value)


# --------------------------------------------------------------------- #
# High-level facade                                                       #
# --------------------------------------------------------------------- #


def build_hal_from_graph(graph, hal_type: str | None = None) -> str:
    """Convenience entry point: parse graph → HAL string.

    Parameters
    ----------
    graph:
        Parsed Klipper profile.
    hal_type:
        ``"remora"`` or ``"parallel"``. If ``None``, reads from
        ``graph.mcu.hal_type`` (default: ``"remora"``).
    """

    from .ini_generator import build_ini_from_graph

    if hal_type is None:
        hal_type = graph.mcu.hal_type if graph.mcu else "remora"

    ini_config = build_ini_from_graph(graph)
    return HalGenerator(hal_type=hal_type).render(ini_config)


__all__ = ["HalGenerator", "build_hal_from_graph"]