"""Render LinuxCNC ``.hal`` files from a parsed Klipper graph.

The HAL file wires LinuxCNC's motion controller to the firmware
channels exposed by the Remora board. The output shape mirrors the
``machine_config/example/goal/linuxcnc.hal`` reference:

* ``[KINS]`` / ``[EMCMOT]`` INI references for the kinematic +
  motion-controller load lines (LinuxCNC substitutes the values).
* SPI enable / reset / status signals.
* Per-joint stepgen wiring via ``remora.joint.N`` channels.
* Tool-change loopback.
* ``loadrt PIDcontroller`` instances for each temperature-controlled
  heater.
* Endstop wiring via ``remora.input.NN`` (X / Y / Z only — the
  extruder does not home).
* Remora SP / PV wiring for every PWM (heater + fan) and every
  temperature sensor.
* One PID configuration block per heater, parameterised by the
  matching ``[BED]`` / ``[EXT0]`` INI section.

The ``parallel`` HAL type keeps the legacy stepgen wiring via
``stepgen.N`` channels for Mesa / parallel-port setups.

PID aliasing
------------
Every heater section in the parsed graph produces one PID controller
named ``PID-<alias>`` where ``<alias>`` comes from a deterministic
mapping table (``heater_bed`` → ``PID-bed``, ``extruder`` →
``PID-ext0``, ``heater_generic chamber`` → ``PID-chamber``, ...).
The HAL stays legible while the INI carries the actual PID values.

Symbolic signal naming
----------------------
Every PWM / Temperature module emits a Remora SP / PV wiring line
that uses a symbolic signal name (e.g. ``pwm_heater_bed``,
``temp_extruder``). The HAL also emits a top-of-file comment
documenting the symbolic → positional Remora mapping so operators can
hand-edit the file without losing the handle.
"""

from __future__ import annotations

import logging
from typing import Mapping

from ..models import Axis, IniConfig, Joint, MachineConfigGraph, SpindleDigital

logger = logging.getLogger("backend.modules.machineconfig.compilers.hal_generator")


# --------------------------------------------------------------------- #
# Heater PID alias mapping                                                 #
# --------------------------------------------------------------------- #


def _heater_pid_alias(heater_id: str) -> str:
    """Map a canonical heater id to a short PID controller name.

    ``heater_bed`` -> ``PID-bed``, ``extruder`` -> ``PID-ext0``,
    ``heater_generic_chamber`` -> ``PID-chamber``. Falls back to
    ``PID-<id>`` for unknown ids so the HAL never breaks on a new
    heater section.
    """
    if heater_id == "heater_bed":
        return "PID-bed"
    if heater_id == "extruder":
        return "PID-ext0"
    if heater_id.startswith("heater_generic_"):
        return f"PID-{heater_id[len('heater_generic_'):]}"
    if heater_id.startswith("heater_"):
        return f"PID-{heater_id[len('heater_'):]}"
    return f"PID-{heater_id}"


def _heater_ini_section(heater_id: str) -> str:
    """Map a canonical heater id to the INI section that carries its PID values.

    ``heater_bed`` -> ``[BED]``, ``extruder`` -> ``[EXT0]``,
    everything else -> ``[<HEATER_ID>]`` upper-cased. The INI
    generator must emit matching sections.
    """
    if heater_id == "heater_bed":
        return "BED"
    if heater_id == "extruder":
        return "EXT0"
    return heater_id.upper()


def _heater_pwm_signal(heater_id: str) -> str:
    """Symbolic signal name for a heater's PWM output."""
    return f"{heater_id}_SP"


def _heater_pv_signal(heater_id: str) -> str:
    """Symbolic signal name for a heater's temperature input."""
    sensor_id = heater_id.removeprefix("heater_") if heater_id.startswith("heater_") else heater_id
    return f"{sensor_id}_PV"


def _fan_pwm_signal(fan_id: str) -> str:
    """Symbolic signal name for a standalone fan's PWM output."""
    return f"{fan_id}_SP"


# --------------------------------------------------------------------- #
# Remora HAL template                                                     #
# --------------------------------------------------------------------- #


REMORA_HAL_HEADER = """\

# machine.hal
# Generated by KlipperToLinuxCNCCompiler (hal_type=remora)
# DO NOT EDIT — re-run the compiler to regenerate.

# Symbolic-to-positional Remora map (for operator reference)
# {symbolic_map}

loadrt [KINS]KINEMATICS
loadrt [EMCMOT]EMCMOT base_period_nsec=[EMCMOT]BASE_PERIOD servo_period_nsec=[EMCMOT]SERVO_PERIOD num_joints=[KINS]JOINTS

# load the Remora real-time component

\t# for STM32 chips
\tloadrt remora-spi SPI_clk_div=64

\t# for LPC17XX chips
\t#loadrt remora_lpc



# estop and SPI comms enable and feedback

\tnet user-enable-out\t<= iocontrol.0.user-enable-out\t\t=> remora.SPI-enable
\tnet user-request-enable <= iocontrol.0.user-request-enable\t=> remora.SPI-reset
\tnet remora-status \t<= remora.SPI-status \t\t=> iocontrol.0.emc-enable-in


# add the remora and motion functions to threads

\taddf remora.read \t\tservo-thread
\taddf motion-command-handler\tservo-thread
\taddf motion-controller \t\tservo-thread
\taddf remora.update-freq \tservo-thread
\taddf remora.write \t\tservo-thread


{joints_block}

# Include your custom HAL commands here
# This file will not be overwritten when you run stepconf again

# tool changing

    net tool-prepare-loopback iocontrol.0.tool-prepare => iocontrol.0.tool-prepared
    net tool-change-loopback iocontrol.0.tool-change => iocontrol.0.tool-changed

{pid_load_block}

# end-stops

    # FOR BIGTREETECH OCTOPUS
{endstop_block}


# remora command outputs (SP = Setpoints sent TO the MCU)

    {sp_block}


# remora command feedbacks (PV = Process Variables read FROM the MCU)

    {pv_block}


{pid_config_block}
{spindle_block}"""


REMORA_JOINT_TEMPLATE = """\

# joint {joint_number} setup

\tsetp remora.joint.{joint_number}.scale \t[JOINT_{joint_number}]SCALE
\tsetp remora.joint.{joint_number}.maxaccel \t[JOINT_{joint_number}]STEPGEN_MAXACCEL

\tnet j{joint_number}pos-cmd \t\tjoint.{joint_number}.motor-pos-cmd \t=> remora.joint.{joint_number}.pos-cmd
\tnet j{joint_number}pos-fb \t\tremora.joint.{joint_number}.pos-fb \t=> joint.{joint_number}.motor-pos-fb
\tnet j{joint_number}enable \t\tjoint.{joint_number}.amp-enable-out \t=> remora.joint.{joint_number}.enable
"""


PARALLEL_HAL_HEADER = """\

loadrt [KINS]KINEMATICS

loadrt thread names=base-thread,servo-thread period1=1000000 period2=1000000

addf motion-command-handler servo-thread
addf motion-controller servo-thread

{joints_block}

net machine-is-on => {enable_signals}
"""


PARALLEL_JOINT_TEMPLATE = """\

# joint {joint_number} setup ({axis_letter_lower} axis)

setp stepgen.{joint_number}.position-scale {scale}
setp stepgen.{joint_number}.steplen 1
setp stepgen.{joint_number}.stepspace 0
setp stepgen.{joint_number}.dirhold 35000
setp stepgen.{joint_number}.dirsetup 35000
setp stepgen.{joint_number}.maxaccel {maxaccel}
"""


# --------------------------------------------------------------------- #
# Builders                                                                #
# --------------------------------------------------------------------- #


class HalGenerator:
    """Render an :class:`IniConfig` + :class:`MachineConfigGraph`
    into a LinuxCNC HAL string.

    The :meth:`render` method is the single public entry point; the
    builders below it are split so the dynamic sections (joints,
    endstops, SP/PV, PID) can grow independently.

    Parameters
    ----------
    hal_type:
        ``"remora"`` (default) or ``"parallel"``. Selects the
        stepgen channel naming and whether timing parameters are
        emitted.
    """

    def __init__(self, hal_type: str = "remora") -> None:
        if hal_type not in {"remora", "parallel"}:
            raise ValueError(
                f"Unsupported hal_type '{hal_type}'; expected 'remora' or 'parallel'"
            )
        self.hal_type = hal_type
        # The graph is optional for callers that only need the
        # joint-block rendering (used by some tests). When supplied
        # the new sections (PID, endstops, SP/PV) are emitted.
        self._graph: MachineConfigGraph | None = None

    def render(
        self,
        config: IniConfig,
        graph: MachineConfigGraph | None = None,
    ) -> str:
        """Render the full HAL from an :class:`IniConfig` and a graph."""
        self._graph = graph
        self._multi_mcu_comment = self._build_multi_mcu_comment()

        joints_block = self._build_joints_block(config.axes)
        enable_signals = self._build_enable_signals(config.axes)

        if self.hal_type == "parallel":
            header = PARALLEL_HAL_HEADER_TEMPLATE = PARALLEL_HAL_HEADER
            return self._multi_mcu_comment + header.format(
                joints_block=joints_block,
                enable_signals=enable_signals,
            )

        # Remora mode — full output with PID, endstops, SP/PV, etc.
        symbolic_map = self._build_symbolic_map()
        pid_load_block = self._build_pid_load_block()
        endstop_block = self._build_endstop_block(config.axes)
        sp_block = self._build_sp_block()
        pv_block = self._build_pv_block()
        pid_config_block = self._build_pid_config_block()
        spindle_block = self._build_spindle_digital_block()

        return (
            self._multi_mcu_comment
            + REMORA_HAL_HEADER.format(
                symbolic_map=symbolic_map,
                joints_block=joints_block,
                pid_load_block=pid_load_block,
                endstop_block=endstop_block,
                sp_block=sp_block,
                pv_block=pv_block,
                pid_config_block=pid_config_block,
                spindle_block="",
            )
            + spindle_block
        )

    # ----- Static block builders ----------------------------------- #

    def _build_multi_mcu_comment(self) -> str:
        """Emit a one-line comment when the profile declares multiple MCUs.

        The Remora HAL loads a single ``remora-spi`` (or equivalent)
        transport regardless of how many MCU sections the profile
        declared. The comment documents this gap so an operator
        hand-editing the file can see what was elided.

        Single-MCU profiles (the historical default) produce no
        comment so the diff against pre-multi-MCU HAL output stays
        clean.
        """
        if self._graph is None:
            return ""
        mcus = self._graph.mcus
        if len(mcus) <= 1:
            return ""
        # Only mention non-remora transports — a profile with two
        # remora boards already fails to emit ``config.txt`` and
        # the deploy step surfaces a separate warning; mentioning
        # it in the HAL adds no value.
        non_remora = {
            name: mcu
            for name, mcu in mcus.items()
            if mcu.connection not in {"remora-spi", "remora-eth"}
        }
        if not non_remora:
            return ""
        joined = ", ".join(
            f"[{name}] {mcu.connection}({mcu.interface or '-'})"
            for name, mcu in non_remora.items()
        )
        return (
            f"# Multi-MCU note: profile declares non-remora transports "
            f"({joined}).\n"
            f"# Pins bound to those MCUs are NOT wired here; the Remora "
            f"HALFILE only loads remora-spi/eth.\n"
        )

    def _build_symbolic_map(self) -> str:
        """Top-of-file comment block mapping symbolic ids to positional pins.

        The Remora firmware itself speaks the positional language
        (``SP.0``, ``PV.0``, ``input.00``); this comment keeps the
        symbolic names next to their integer index so an operator
        hand-editing the file can find the right pin by name.
        """
        if self._graph is None:
            return "# (no graph supplied — symbolic map omitted)"

        lines: list[str] = []
        sp_index = 0
        pv_index = 0

        # Heater PWMs and their associated temperature sensors come
        # first, in canonical name order, matching ``config.txt``.
        for heater_id in sorted(self._graph.heaters.keys()):
            pwm_signal = _heater_pwm_signal(heater_id)
            pv_signal = _heater_pv_signal(heater_id)
            lines.append(f"# {pwm_signal:<28} => remora.SP.{sp_index}")
            lines.append(f"# {pv_signal:<28} <= remora.PV.{pv_index}")
            sp_index += 1
            pv_index += 1

        # Standalone fans get their own SP only.
        for fan in sorted(self._graph.fans.values(), key=lambda f: f.name):
            pwm_signal = _fan_pwm_signal(fan.name)
            lines.append(f"# {pwm_signal:<28} => remora.SP.{sp_index}")
            sp_index += 1

        return "\n".join(lines) if lines else "# (no symbolic map entries)"

    def _build_pid_load_block(self) -> str:
        """``loadrt PIDcontroller`` and per-controller ``addf`` lines."""
        if self._graph is None:
            return ""
        pid_aliases = [
            _heater_pid_alias(h) for h in sorted(self._graph.heaters.keys())
        ]
        if not pid_aliases:
            return ""
        names = ",".join(pid_aliases)
        lines = ["# PID controllers for heaters", ""]
        lines.append(f"    loadrt PIDcontroller names={names}")
        for alias in pid_aliases:
            lines.append(f"    addf {alias}.compute servo-thread")
        return "\n".join(lines) + "\n"

    def _build_endstop_block(self, axes: list[Axis]) -> str:
        """Emit one ``net`` per non-extruder joint mapping a Remora input."""
        lines: list[str] = []
        for joint in self._iter_stepgen_joints(axes):
            axis_lower = joint.axis_letter.lower()
            input_index = joint.joint_number
            label = f"{axis_lower}-stop"
            lines.append(
                f"    net {label:<8} remora.input.{input_index:02d}    => "
                f"joint.{joint.joint_number}.home-sw-in joint.{joint.joint_number}.neg-lim-sw-in"
            )
        if not lines:
            return ""
        return "\n".join(lines) + "\n"

    def _build_sp_block(self) -> str:
        """``net`` lines wiring each PWM module to its Remora SP channel."""
        if self._graph is None:
            return ""
        lines: list[str] = []
        sp_index = 0
        for heater_id in sorted(self._graph.heaters.keys()):
            lines.append(
                f"    net {_heater_pwm_signal(heater_id):<28} => remora.SP.{sp_index}"
            )
            sp_index += 1
        for fan in sorted(self._graph.fans.values(), key=lambda f: f.name):
            lines.append(
                f"    net {_fan_pwm_signal(fan.name):<28} => remora.SP.{sp_index}"
            )
            sp_index += 1
        if not lines:
            return ""
        return "\n".join(lines) + "\n"

    def _build_pv_block(self) -> str:
        """``net`` lines wiring each temperature sensor to a Remora PV channel."""
        if self._graph is None:
            return ""
        lines: list[str] = []
        pv_index = 0
        for heater_id in sorted(self._graph.heaters.keys()):
            lines.append(
                f"    net {_heater_pv_signal(heater_id):<28} <= remora.PV.{pv_index}"
            )
            pv_index += 1
        if not lines:
            return ""
        return "\n".join(lines) + "\n"

    def _build_pid_config_block(self) -> str:
        """Per-heater PID configuration block reading the INI helper."""
        if self._graph is None:
            return ""
        blocks: list[str] = []
        for heater_id in sorted(self._graph.heaters.keys()):
            alias = _heater_pid_alias(heater_id)
            section = _heater_ini_section(heater_id)
            pwm_signal = _heater_pwm_signal(heater_id)
            pv_signal = _heater_pv_signal(heater_id)
            blocks.append(
                _PID_CONFIG_BLOCK_TEMPLATE.format(
                    alias_title=alias.lstrip("PID-").title(),
                    alias=alias,
                    section=section,
                    pwm_signal=pwm_signal,
                    pv_signal=pv_signal,
                )
            )
        return "\n".join(blocks) + ("\n" if blocks else "")

    # ----- SpindleDigital digital block (vfdmod <-> pyvcp hooks) ----------- #

    def _build_spindle_digital_block(self) -> str:
        """Emit one vfdmod <-> pyvcp wiring block per digital spindle.

        Iterates :attr:`MachineConfigGraph.spindle_digitals` and
        delegates to :meth:`_build_single_spindle_block`. The bare
        ``[spindle]`` form produces a single block identical to the
        historical output (no signal-name suffix). Named forms like
        ``[spindle test]`` get their pyvcp signal names suffixed by
        ``_test`` so multiple spindles do not collide on the shared
        ``TargetRpm`` / ``at-speed1`` / ... pyvcp signal names.
        """
        if self._graph is None or not self._graph.spindle_digitals:
            return ""

        blocks: list[str] = []
        for spindle_id, spindle in self._graph.spindle_digitals.items():
            blocks.append(
                self._build_single_spindle_block(spindle_id, spindle)
            )
        return "\n".join(blocks)

    @staticmethod
    def _spindle_pyvcp_suffix(spindle_id: str) -> str:
        """Return the pyvcp-signal suffix for a spindle canonical id.

        Bare form (``spindle_digital``) → empty suffix so the
        generated HAL is byte-identical to the historical single
        output. Named form (``spindle_digital_test``) → ``_test`` so
        ``pyvcp.TargetRpm_test`` / ``pyvcp.at-speed1_test`` stay
        distinct across multiple spindles.
        """
        if spindle_id == "spindle_digital":
            return ""
        prefix = "spindle_digital_"
        if spindle_id.startswith(prefix):
            return "_" + spindle_id[len(prefix):]
        return "_" + spindle_id

    def _build_single_spindle_block(
        self, spindle_id: str, digital: SpindleDigital
    ) -> str:
        """Emit the vfdmod <-> pyvcp wiring block for one digital spindle.

        Renders one ``net`` line per populated ``*_signal`` field on
        :class:`~.klipper_models.SpindleDigital`, and one
        commented ``# net ...  # TODO: manual hookup`` line per
        unpopulated field, so an operator editing the HAL by hand
        can see where each signal is supposed to live. Always emits
        the trailing ``loadusr -W vfdmod vfd.ini`` so vfdmod is
        loaded even when the user has not filled any signal yet.

        The pyvcp-side signal name is suffixed by the canonical id
        (e.g. ``pyvcp.TargetRpm_test``) when ``spindle_id`` is not
        the bare ``spindle_digital`` form, so multiple spindles do
        not collide on shared pyvcp signal names.
        """
        suffix = self._spindle_pyvcp_suffix(spindle_id)

        # (display_name, vfdmod_path, attr_name). ``display_name``
        # is the default signal name the user expects to find in
        # pyvcp (matches the vfdmod parameter keys). The ordering
        # below matches the documentation order: status / speed
        # feedback first, then communication, then the at-speed
        # tie-up handled separately.
        signals: list[tuple[str, str, str]] = [
            ("TargetRpm", "vfdmod.parameters.TargetRpm", "target_rpm_signal"),
            ("TargetFrequency", "vfdmod.parameters.TargetFrequency", "target_frequency_signal"),
            ("rpm-out", "vfdmod.spindle.rpm-out", "rpm_out_signal"),
            ("is-connected", "vfdmod.rs485.is-connected", "is_connected_signal"),
            ("error-count", "vfdmod.rs485.error-count", "error_count_signal"),
            ("last-error", "vfdmod.rs485.last-error", "last_error_signal"),
        ]

        lines: list[str] = []
        lines.append(f"# Spindle digital [{spindle_id}] (vfdmod <-> pyvcp) signal wiring")
        lines.append(
            "# Populated signals below are emitted as live 'net' lines;"
            " unpopulated signals appear as commented placeholders."
        )
        lines.append("# Edit this block to wire the signals into your VFD.")
        lines.append("")

        for default_name, vfdmod_path, attr in signals:
            value = getattr(digital, attr)
            pyvcp_default = f"{default_name}{suffix}"
            if value:
                pyvcp_value = f"{value}{suffix}" if suffix else value
                # 18-char column for the signal name so it lines up
                # with the 16-char ``# net <name>`` column used by
                # the placeholder lines below (the extra 2 chars
                # account for the absent ``# `` prefix).
                lines.append(
                    f"net {value:<18} {vfdmod_path:<38} pyvcp.{pyvcp_value}"
                )
            else:
                lines.append(
                    f"# net {default_name:<16} {vfdmod_path:<38} pyvcp.{pyvcp_default}"
                    f"   # TODO: manual hookup"
                )

        # at-speed1 + at-speed2 share a single 'net' line that ties
        # vfdmod.spindle.at-speed to both pyvcp inputs. Emit the
        # live line when either side is populated; when neither is,
        # emit the whole line as a placeholder.
        at1 = digital.at_speed1_signal
        at2 = digital.at_speed2_signal
        pyvcp_left_default = f"at-speed1{suffix}"
        pyvcp_right_default = f"at-speed2{suffix}"
        if at1 or at2:
            left = at1 or "at-speed1"
            right = at2 or "at-speed2"
            pyvcp_left = f"{left}{suffix}" if suffix else left
            pyvcp_right = f"{right}{suffix}" if suffix else right
            lines.append(
                f"net spindle-at-speed{suffix} vfdmod.spindle.at-speed"
                f" <= pyvcp.{pyvcp_left} <= pyvcp.{pyvcp_right}"
            )
        else:
            lines.append(
                f"# net spindle-at-speed{suffix} vfdmod.spindle.at-speed"
                f" <= pyvcp.{pyvcp_left_default} <= pyvcp.{pyvcp_right_default}"
                "   # TODO: manual hookup"
            )

        lines.append("loadusr -W vfdmod vfd.ini")
        return "\n".join(lines) + "\n"

    # ----- Joint block builders (shared between hal types) ---------- #

    def _iter_stepgen_joints(self, axes: list[Axis]) -> list[Joint]:
        """Return the Cartesian stepgen joints (X / Y / Z) in order.

        The extruder (axis letter ``A``) is excluded — its endstop
        is not wired on a 3D-printer setup. The Remora firmware
        expects one input pin per Cartesian joint starting at
        ``input.00``; the joint number matches the Remora input
        index directly.
        """
        ordered: list[Joint] = []
        for axis in axes:
            if axis.letter not in {"X", "Y", "Z"}:
                continue
            for joint in axis.joints:
                ordered.append(joint)
        return ordered

    def _build_joints_block(self, axes: list[Axis]) -> str:
        """Render one joint block per joint across all axes."""
        chunks: list[str] = []
        for axis in axes:
            for joint in axis.joints:
                if self.hal_type == "parallel":
                    chunks.append(self._render_parallel_joint(joint))
                else:
                    chunks.append(self._render_remora_joint(joint))
        return "\n".join(chunks)

    def _render_remora_joint(self, joint: Joint) -> str:
        """Render the Remora-style joint block (uses INI section refs)."""
        return REMORA_JOINT_TEMPLATE.format(
            joint_number=joint.joint_number,
        )

    def _render_parallel_joint(self, joint: Joint) -> str:
        """Render the legacy stepgen-style joint block."""
        return PARALLEL_JOINT_TEMPLATE.format(
            axis_letter=joint.axis_letter,
            axis_letter_lower=joint.axis_letter.lower(),
            joint_number=joint.joint_number,
            scale=self._fmt(joint.scale),
            maxaccel=self._fmt(joint.stepgen_maxaccel),
        )

    def _build_enable_signals(self, axes: list[Axis]) -> str:
        """Build the ``net machine-is-on => ...`` signal list (parallel mode)."""
        signals: list[str] = []
        for axis in axes:
            for joint in axis.joints:
                if self.hal_type == "parallel":
                    signals.append(f"stepgen.{joint.joint_number}.enable")
                else:
                    # Remora mode uses the joint channel as the enable
                    # target. The ``net machine-is-on => ...`` line is
                    # emitted only in parallel mode today; the remora
                    # mode wires the SPI enable separately.
                    continue
        return " ".join(signals)

    # ----- Helpers ------------------------------------------------ #

    @staticmethod
    def _fmt(value: float | int) -> str:
        """Format a numeric value, dropping trailing ``.0`` on integers."""
        if isinstance(value, bool):
            return str(value)
        if isinstance(value, int):
            return str(value)
        if isinstance(value, float):
            if value.is_integer():
                return str(int(value))
            return f"{value:.4f}".rstrip("0").rstrip(".")
        return str(value)


_PID_CONFIG_BLOCK_TEMPLATE = """\

## {alias_title} PID configuration

    net remora-status  => {alias}.auto
    net {pwm_signal}  => {alias}.SP
    net {pv_signal}  => {alias}.PV
    net {pwm_signal}  => {alias}.CV

    setp {alias}.pOnM      [{section}]PID_PONM
    setp {alias}.direction [{section}]PID_DIR
    setp {alias}.KP        [{section}]PID_KP
    setp {alias}.KI        [{section}]PID_KI
    setp {alias}.KD        [{section}]PID_KD
    setp {alias}.SPmin     [{section}]PID_SPMIN
    setp {alias}.SPmax     [{section}]PID_SPMAX
    setp {alias}.CVmin     [{section}]PID_CVMIN
    setp {alias}.CVmax     [{section}]PID_CVMAX
"""


# --------------------------------------------------------------------- #
# High-level facade                                                       #
# --------------------------------------------------------------------- #


def build_hal_from_graph(
    graph: MachineConfigGraph,
    hal_type: str | None = None,
) -> str:
    """Convenience entry point: parse graph → HAL string.

    Parameters
    ----------
    graph:
        Parsed Klipper profile.
    hal_type:
        ``"remora"`` or ``"parallel"``. If ``None``, reads from
        ``graph.mcu.hal_type`` (default: ``"remora"``).
    """
    from .ini_generator import build_ini_from_graph

    if hal_type is None:
        hal_type = graph.mcu.hal_type if graph.mcu else "remora"

    ini_config = build_ini_from_graph(graph)
    return HalGenerator(hal_type=hal_type).render(ini_config, graph)


__all__ = [
    "HalGenerator",
    "build_hal_from_graph",
    "_heater_pid_alias",
    "_heater_ini_section",
    "_heater_pwm_signal",
    "_heater_pv_signal",
    "_fan_pwm_signal",
]
