"""Template generation orchestrator.

Generates the per-machine template set from a profile ``.cfg``:

    profiles/<path>.cfg  ->  machines/<target_folder>/<stem>/configs/
                               machine.cfg              (verbatim source copy)
                               hardware.json             (real, existing generator)
                               machine.ini               (live INI — see ini_template_generator)
                               machine.hal               (real compiled wiring + webgui pin
                                                           catalog reference — see
                                                           _render_machine_hal)
                               config_<mcu_id>.txt       (Remora firmware payload, one per
                                                           Remora MCU — only when the machine
                                                           compiles; see _render_machine_hal)
                               vfd_<mcu_id>.ini          (VFD serial settings, one per
                                                           vfd_rs485 MCU — same condition)
                               custom.hal                (loads webgui, sources the file below)
                               webgui_connections.hal    (starter — never overwritten once it exists)
                               postgui_call_list.hal     (empty placeholder; referenced by machine.ini)
                               tool.tbl                  (empty tool table; referenced by machine.ini)

The MCU sidecars (``config_<mcu_id>.txt``, ``vfd_<mcu_id>.ini``) are
keyed by MCU id, not a fixed name — a machine with two Remora boards
gets ``config_mcu_a.txt`` and ``config_mcu_b.txt``, never one file two
boards silently collide on. They only appear when
``services.halcompiler`` actually assembled the machine (the same
condition that puts real wiring in ``machine.hal`` instead of the
catalog fallback) and are not in :data:`GENERATED_FILES` — that list
is the fixed files every generation writes; these are as dynamic as
the machine's own MCU list.

The machine name is the source file stem. When the target machine
folder already exists :class:`MachineExistsError` is raised unless
``confirm_override`` is set — the router translates that into a 409
the frontend confirms before retrying. ``webgui_connections.hal`` is
the one exception to "regenerate wipes everything": its content is
preserved across a regenerate (or seeded with real spindle/heater
bindings on first generation, see
:func:`_render_webgui_connections_starter`) because it's where the
operator hand-wires the ``webgui`` HAL component to their
spindle/VFD/etc.
"""

from __future__ import annotations

import json
import logging
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, List, Optional

from machineconfig_parser import parse_config
from domain_file_services import paths
from domain_file_services.ConfigFileService import ConfigFileService
from domain_file_services.MachineFileService import MachineFileService
from services.halcompiler import (
    MachineValidator,
    UnsupportedMcuError,
    assemble_machine,
    render_hal,
    render_webgui_connections,
    validate_machine,
)
from services.machineconfig import AxisBuilder, AxisMappingPolicy
from services.machineconfig.hardware_json_generator import build_hardware_json

from .hal_template_generator import render_hal_template
from .ini_template_generator import render_ini_template
from .pin_catalog import PinCatalog, build_pin_catalog

logger = logging.getLogger("backend.services.machinetemplates")

#: Basenames every generation writes into ``configs/``.
GENERATED_FILES = (
    "machine.cfg",
    "hardware.json",
    "machine.ini",
    "machine.hal",
    "custom.hal",
    "webgui_connections.hal",
    "postgui_call_list.hal",
    "tool.tbl",
)

#: The venv interpreter + machine backend entrypoint ``custom.hal``
#: loads as the ``webgui`` HAL userspace component. Both paths are
#: absolute (repo-root-relative), matching ``install.sh``'s venv
#: layout, so the generated INI works regardless of where LinuxCNC's
#: working directory ends up at boot.
_VENV_PYTHON = paths.PROJECT_ROOT / "backend" / "venv" / "bin" / "python"
_MACHINE_MAIN = paths.PROJECT_ROOT / "backend" / "machine" / "main.py"

CUSTOM_HAL_TEMPLATE = """\
# custom.hal - generated by the LinuxCNC_UI machine templates
#
# Add any extra loadrt/loadusr directives your machine needs (VFD
# driver, extra components, ...) above the "webgui" line below —
# webgui_connections.hal wires them together and always runs last.

# Force loadusr to name the component 'webgui' and wait (-W) for it
# to be ready before webgui_connections.hal references its pins.
loadusr -W -n webgui {python} {main}

source webgui_connections.hal
"""

#: Written only the first time a machine is generated — see the
#: module docstring. Machine-specific HAL wiring (spindle VFD,
#: overrides, ...) belongs here, not in ``custom.hal``.
WEBGUI_CONNECTIONS_HEADER = """\
# webgui_connections.hal - wire the "webgui" HAL component's pins
# into your machine (spindle VFD, overrides, ...).
#
# custom.hal always sources this file. Unlike every other generated
# file, this one is NOT overwritten when the machine is regenerated
# — edit it freely. See machine.hal for the full pin catalog and
# per-pin connection hints.
#
# The block below (if any) was auto-generated from this machine's
# spindle/heater definitions the first time it was generated. Nothing
# here is magic — it's the same net/pin-naming convention documented
# in machine.hal's own pin-reference appendix, just pre-wired for the
# tools this profile already declares.
"""


def _render_webgui_connections_starter(payload: Dict[str, Any]) -> str:
    """The first-generation seed for ``webgui_connections.hal``.

    ``render_webgui_connections`` (``services.halcompiler``) covers
    spindle + heater bindings today; anything it has no tool to bind
    (no spindle, no heater, or a different tool type entirely) simply
    adds nothing, so the header alone is exactly the old static
    starter text.
    """
    bindings = render_webgui_connections(payload)
    if not bindings:
        return WEBGUI_CONNECTIONS_HEADER
    return WEBGUI_CONNECTIONS_HEADER + "\n" + bindings

POSTGUI_CALL_LIST_TEMPLATE = """\
# postgui_call_list.hal - generated by the LinuxCNC_UI machine templates
# HAL commands here run once the GUI has loaded. Empty by default.
"""

TOOL_TABLE_TEMPLATE = """\
; tool.tbl - generated by the LinuxCNC_UI machine templates (no tools yet)
"""


def _compile_machine(
    machine_name: str, payload: Dict[str, Any], catalog: PinCatalog
) -> tuple[str, Dict[str, str]]:
    """Real compiled wiring when the machine compiles; an honest fallback when it doesn't.

    Returns ``(machine_hal_text, sidecar_files)`` — ``sidecar_files``
    maps a bare filename (``config_<mcu_id>.txt``, ``vfd_<mcu_id>.ini``
    — see :class:`.hal_fragment_models.HalFragment.files`) to its
    content, one entry per MCU that needed one. Keyed by MCU id, not a
    fixed name, precisely so a machine with two Remora boards gets
    ``config_mcu_a.txt`` *and* ``config_mcu_b.txt`` instead of the
    second one silently overwriting the first.

    ``machine.hal`` used to be pure documentation — every line a
    comment, the operator wiring everything by hand off the pin
    catalog. Now that ``services.halcompiler`` can actually emit
    motion/spindle/heater wiring from ``hardware.json``, that catalog
    only needs to cover what the compiler doesn't handle yet (the
    webgui/UI-bindings pass isn't built) — so it becomes a trailing
    reference section instead of the whole file.

    A profile that doesn't validate yet (no ``[mcu]`` declared, a
    connection type with no router, ...) must not crash generation —
    that would regress every profile the old catalog-only generator
    used to handle unconditionally. Falling back to the full catalog,
    with a comment explaining why, keeps the file honest without ever
    raising out of ``generate_machine_templates`` — and correctly
    yields no sidecar files, since nothing was actually assembled.
    """
    diagnostics = validate_machine(payload)
    if MachineValidator.has_errors(diagnostics):
        details = "\n".join(str(d) for d in diagnostics if d.is_error)
        return _fallback_machine_hal(machine_name, catalog, details), {}

    try:
        fragment = assemble_machine(payload)
    except UnsupportedMcuError as exc:
        return _fallback_machine_hal(machine_name, catalog, str(exc)), {}

    appendix = render_hal_template(machine_name, catalog, standalone=False)
    hal_text = render_hal(fragment).rstrip("\n") + "\n\n" + appendix
    return hal_text, dict(fragment.files)


def _fallback_machine_hal(machine_name: str, catalog: PinCatalog, reason: str) -> str:
    reason_lines = [line for line in reason.strip().splitlines() if line.strip()]
    commented_reason = "\n".join(f"# {line}" for line in reason_lines)
    header = (
        "# machine.hal - the HAL compiler could not generate real wiring\n"
        "# for this machine yet:\n"
        f"{commented_reason}\n"
        "#\n"
        "# Falling back to the pin-catalog reference below — wire it by\n"
        "# hand, or fix the issue above and regenerate.\n"
        "#\n"
    )
    return header + render_hal_template(machine_name, catalog)


class MachineExistsError(Exception):
    """Raised when the target machine folder already exists.

    Attributes:
        machine: The machine name (= source file stem).
        existing_files: Relative paths currently on disk under the
            machine folder.
    """

    def __init__(self, machine: str, existing_files: List[str]) -> None:
        self.machine = machine
        self.existing_files = existing_files
        super().__init__(
            f"Machine '{machine}' already exists "
            f"({len(existing_files)} file(s)); pass confirm_override to replace it."
        )


@dataclass(frozen=True)
class GenerateResult:
    """Outcome of one :func:`generate_machine_templates` run."""

    machine: str
    target_folder: str
    files: List[str] = field(default_factory=list)


def _posix(path: Path) -> str:
    return str(path).replace("\\", "/")


def _normalize_target(target_folder: str) -> str:
    """Normalize the optional target folder to a clean relative prefix."""
    parts = [p for p in (target_folder or "").replace("\\", "/").split("/") if p]
    if any(p in {".", ".."} for p in parts):
        raise ValueError(f"Invalid target folder: {target_folder!r}")
    return "/".join(parts)


def _machine_configs_relpath(machine_name: str, target_folder: str) -> str:
    prefix = f"{target_folder}/" if target_folder else ""
    return f"{prefix}{machine_name}/configs"


def resolve_machine_configs_dir(
    machine_service: MachineFileService, machine_path: str
) -> Path:
    """Resolve an operator-supplied ``machine_path`` to its ``configs/`` dir.

    Accepts either the machine's own folder (``"PrintNC"``) or the
    configs folder directly (``"PrintNC/configs"``) so callers don't
    need to know the internal ``configs/`` nesting convention. Used
    by the ``/deploy`` endpoint and :class:`MachineLifecycleService`
    to find what to copy into ``machine_config/active/``.

    Raises:
        ValueError: ``machine_path`` escapes ``machines/``.
    """
    target = machine_service.safe_join(machine_path)
    if target.is_dir() and target.name == "configs":
        return target
    return target / "configs"


def generate_machine_templates(
    profile_path: str,
    target_folder: str = "",
    confirm_override: bool = False,
    *,
    config_service: Optional[ConfigFileService] = None,
    machine_service: Optional[MachineFileService] = None,
    catalog: Optional[PinCatalog] = None,
) -> GenerateResult:
    """Generate the template set for ``profile_path``.

    Args:
        profile_path: Path relative to ``profiles/``.
        target_folder: Optional folder under ``machines/`` to nest the
            machine folder in (supports operator grouping).
        confirm_override: Replace an existing machine folder without
            the existence check.
        config_service: Override for tests (defaults to the factory).
        machine_service: Override for tests (defaults to the factory).
        catalog: Pre-built pin catalog override (defaults to the
            preloaded services).

    Raises:
        FileNotFoundError: The profile does not exist.
        ValueError: Path traversal or invalid target folder.
        MachineExistsError: Target exists and ``confirm_override`` is false.
    """
    config_service = config_service or ConfigFileService()
    machine_service = machine_service or MachineFileService()

    source = config_service.safe_join(profile_path)
    if not source.exists() or not source.is_file():
        raise FileNotFoundError(f"Profile not found: {profile_path}")

    machine_name = source.stem
    target_folder = _normalize_target(target_folder)
    configs_rel = _machine_configs_relpath(machine_name, target_folder)
    configs_dir = machine_service.safe_join(configs_rel)

    if configs_dir.exists() and not confirm_override:
        existing = sorted(
            str(p.relative_to(machine_service.root)).replace("\\", "/")
            for p in configs_dir.rglob("*")
            if p.is_file()
        )
        raise MachineExistsError(machine_name, existing)

    # Parse once, feed both the wire hardware.json AND the richer
    # in-memory Axis/Joint objects (which carry velocity/accel/scale/
    # home fields hardware.json doesn't serialise) to the INI
    # renderer. SPLIT_INTO_MULTIPLE_JOINTS (rather than the default
    # merge policy) is what makes a multi-motor axis — a dual-Y
    # gantry declared as ``[stepper_y]`` + ``[stepper_y1]`` — render
    # one [JOINT_N] per physical motor instead of collapsing them.
    graph = parse_config(source)
    payload: Dict[str, Any] = build_hardware_json(graph, machine_name)
    axes = AxisBuilder(graph, policy=AxisMappingPolicy.SPLIT_INTO_MULTIPLE_JOINTS).build()

    if catalog is None:
        catalog = build_pin_catalog()

    # webgui_connections.hal is the one file a regenerate must not
    # clobber — capture whatever's there (if anything) before the
    # directory gets wiped, and write it back verbatim afterward.
    webgui_connections_path = configs_dir / "webgui_connections.hal"
    existing_webgui_connections = (
        webgui_connections_path.read_bytes() if webgui_connections_path.exists() else None
    )

    machine_service.clear_directory(configs_dir)

    # 1. Verbatim source copy (provenance).
    (configs_dir / "machine.cfg").write_bytes(source.read_bytes())

    # 2. The real runtime contract.
    (configs_dir / "hardware.json").write_text(
        json.dumps(payload, indent=2) + "\n", encoding="utf-8"
    )

    # 3. The live INI — including PID sections for every PID heater
    # (machine.hal's `setp PID-<id>.KP [<SECTION>]PID_KP` lines are
    # ini-var references; without this they resolve to nothing).
    (configs_dir / "machine.ini").write_text(
        render_ini_template(machine_name, axes, payload.get("tools")), encoding="utf-8"
    )

    # 4. The real compiled wiring (motion/spindle/heaters), with the
    # webgui pin catalog trailing as reference — or, if this machine
    # doesn't compile yet, the catalog-only fallback (see docstring).
    # Compiling also yields the MCU sidecars (Remora config.txt, VFD
    # serial .ini) — empty when the fallback ran, since nothing was
    # actually assembled.
    hal_text, mcu_sidecar_files = _compile_machine(machine_name, payload, catalog)
    (configs_dir / "machine.hal").write_text(hal_text, encoding="utf-8")

    # 4b. One file per MCU that needed one — keyed by MCU id (see
    # module docstring) so a second Remora board never overwrites the
    # first board's config.txt.
    sidecar_files = [
        f"{configs_rel}/{filename}" for filename in sorted(mcu_sidecar_files)
    ]
    for filename, content in mcu_sidecar_files.items():
        (configs_dir / filename).write_text(content, encoding="utf-8")

    # 5. custom.hal always loads webgui and sources the file below —
    # regenerated every time so a repo-layout change (e.g. a venv
    # path change) is never stale.
    (configs_dir / "custom.hal").write_text(
        CUSTOM_HAL_TEMPLATE.format(python=_posix(_VENV_PYTHON), main=_posix(_MACHINE_MAIN)),
        encoding="utf-8",
    )

    # 6. webgui_connections.hal — restore hand-wiring if it existed,
    # otherwise seed it with real spindle/heater bindings (or, if this
    # machine declares neither, the same static header as before).
    webgui_connections_path.write_bytes(
        existing_webgui_connections
        if existing_webgui_connections is not None
        else _render_webgui_connections_starter(payload).encode("utf-8")
    )

    # 7. Referenced by machine.ini but not part of the "artifacts a
    # profile drives" story — empty placeholders so LinuxCNC has
    # something to load.
    (configs_dir / "postgui_call_list.hal").write_text(
        POSTGUI_CALL_LIST_TEMPLATE, encoding="utf-8"
    )
    (configs_dir / "tool.tbl").write_text(TOOL_TABLE_TEMPLATE, encoding="utf-8")

    files = [
        f"{configs_rel}/{name}"
        for name in GENERATED_FILES
        if (configs_dir / name).exists()
    ] + sidecar_files
    logger.info(
        "Generated machine templates for '%s' under %s", machine_name, configs_rel
    )
    return GenerateResult(
        machine=machine_name, target_folder=target_folder, files=files
    )


__all__ = [
    "GENERATED_FILES",
    "GenerateResult",
    "MachineExistsError",
    "generate_machine_templates",
    "resolve_machine_configs_dir",
]
