"""``machine.hal`` template renderer.

Renders the complete HAL pin catalog of the ``webgui`` userspace
component (see :mod:`.pin_catalog`) as a commented wiring guide:

* every pin with its HAL type and direction,
* a copy-paste-ready ``net`` suggestion line per pin (naming generic
  LinuxCNC HAL components where the catalog has a hint),
* static configuration constants documented inline (never wired),
* unconnected placeholder slots listed for completeness.

Every line is a comment — the file is a template, not a runnable HAL
configuration. The operator un-comments and edits the ``net`` lines to
wire the machine.
"""

from __future__ import annotations

from typing import List

from .pin_catalog import (
    COMPONENT_NAME,
    PinCatalog,
    PinContainerDescriptor,
    PinDescriptor,
)

TEMPLATE_HEADER = """\
# machine.hal - TEMPLATE (generated by the LinuxCNC_UI machine templates)
# Machine: {machine_name}
#
# !!! TEMPLATE - NOT FUNCTIONAL !!!
# This file documents the HAL surface of the "{component}" userspace
# component ({pin_count} pins). Every wiring line below is a comment -
# un-comment and edit the signal names to wire your machine.
#
# Direction legend:
#   in  -> the webgui pin is a HAL input:  net <signal> => webgui.<pin>
#   out -> the webgui pin is a HAL output: net <signal> <= webgui.<pin>
"""

#: Used instead of :data:`TEMPLATE_HEADER` when this catalog is
#: appended after real, compiled HAL text rather than standing alone —
#: see ``generator._render_machine_hal``. The file above this point
#: already loaded and wired the machine; this section is reference
#: only, for hand-wiring ``webgui_connections.hal``.
APPENDIX_HEADER = """\
#{sep}
# WEBGUI PIN REFERENCE ({pin_count} pins on the "{component}" component)
#{sep}
# Everything above this line is real, compiled HAL. Everything below
# is documentation only (every line is a comment) — wire the pins you
# need in webgui_connections.hal using the net lines as a starting
# point.
#
# Direction legend:
#   in  -> the webgui pin is a HAL input:  net <signal> => webgui.<pin>
#   out -> the webgui pin is a HAL output: net <signal> <= webgui.<pin>
"""

_GROUP_TITLES = {
    "tools": "Tools",
    "sensors": "Sensors / Temperature",
    "state": "Machine state",
}


def _render_pin(pin: PinDescriptor) -> List[str]:
    if pin.kind == "unconnected":
        return [
            f"# {pin.field:<34} (unconnected placeholder - no pin created)",
        ]
    if pin.kind == "static":
        return [
            f"# {pin.field:<34} (static config constant = {pin.value} - never wired)",
        ]

    lines = [
        f"# {pin.short_pin:<34} {pin.hal_type:<6} {pin.direction:<4} {pin.connect_hint}:",
    ]
    if pin.direction == "in":
        lines.append(f"#   net {pin.field.replace('.', '-')} => {pin.pin_name}")
    else:
        lines.append(f"#   net {pin.field.replace('.', '-')} <= {pin.pin_name}")
    return lines


def _render_container(container: PinContainerDescriptor) -> List[str]:
    title = _GROUP_TITLES.get(container.group, container.group.title())
    owner = container.owner_id or "<unnamed>"
    lines = [
        "",
        "#" + "-" * 74,
        f"# {title} / {container.container} : {owner}",
        "#" + "-" * 74,
    ]
    for pin in container.pins:
        lines.extend(_render_pin(pin))
    return lines


def render_hal_template(
    machine_name: str, catalog: PinCatalog, *, standalone: bool = True
) -> str:
    """Render the pin catalog as a commented wiring reference.

    Args:
        machine_name: Machine name for the header comment.
        catalog: The pin catalog (see :mod:`.pin_catalog`).
        standalone: ``True`` (default) renders this as the whole file
            — a `machine.hal` with no compiled wiring, the historical
            behaviour. ``False`` renders it as an appendix meant to
            follow real, compiled HAL text in the same file (see
            ``generator._render_machine_hal``): a shorter header that
            doesn't claim the whole file is inert, and no "next steps"
            footer describing a template that no longer applies.
    """
    if standalone:
        header = TEMPLATE_HEADER.format(
            machine_name=machine_name,
            component=COMPONENT_NAME,
            pin_count=catalog.total_pins(),
        )
    else:
        header = APPENDIX_HEADER.format(
            component=COMPONENT_NAME, pin_count=catalog.total_pins(), sep="-" * 74
        )
    lines: List[str] = [header.rstrip()]

    for group in catalog.groups():
        for container in catalog.for_group(group):
            lines.extend(_render_container(container))

    if standalone:
        lines.extend(
            [
                "",
                "#" + "-" * 74,
                "# Next steps",
                "#" + "-" * 74,
                "# 1. Wire each pin above with a named signal (un-comment the net lines).",
                "# 2. Load the realtime components your machine needs (motmod / stepgen / vfdmod / ...).",
                "# 3. Reference this file from machine.ini ([HAL] HALFILE = machine.hal).",
                "# 4. Do NOT flash config.txt - it is intentionally not generated for templates.",
                "",
            ]
        )
    return "\n".join(lines)


__all__ = ["render_hal_template"]
