"""``machine.ini`` template renderer.

The template is intentionally **not functional**: only the ``[EMC]``
``MACHINE`` name is written as a live value (LinuxCNC refuses to start
without it and the operator picked the name). Every other section is a
commented skeleton the operator fills in by hand. The axis / joint
sections are derived from the freshly generated ``hardware.json``
payload so the skeleton always matches the profile's kinematics.
"""

from __future__ import annotations

from typing import Any, Dict, List

TEMPLATE_HEADER = """\
# machine.ini - TEMPLATE (generated by the LinuxCNC_UI machine templates)
# Machine: {machine_name}
#
# !!! TEMPLATE - NOT FUNCTIONAL !!!
# Only the [EMC] MACHINE name below is live. Uncomment and complete the
# remaining sections before starting LinuxCNC with this file. This file
# is a hand-editing starting point, not a runnable configuration.
"""


def render_ini_template(machine_name: str, hardware_payload: Dict[str, Any]) -> str:
    """Render the ``machine.ini`` template text.

    Args:
        machine_name: Machine name (the source ``.cfg`` file stem) —
            written live into ``[EMC] MACHINE``.
        hardware_payload: The freshly built hardware.json dict; its
            ``axes`` / ``joints`` entries drive the skeleton sections.
    """
    lines: List[str] = [TEMPLATE_HEADER.format(machine_name=machine_name).rstrip()]

    lines.extend(
        [
            "",
            "[EMC]",
            f"MACHINE = {machine_name}",
            "# DEBUG = 0",
            "",
            "# [DISPLAY]",
            "# DISPLAY = axis",
            "# EDITOR = gedit",
            "",
            "# [TASK]",
            "# TASK = milltask",
            "# CYCLE_TIME = 0.010",
            "",
            "# [RS274NGC]",
            "# PARAMETER_FILE = linuxcnc.var",
            "",
            "# [EMCMOT]",
            "# EMCMOT = motmod",
            "# COMM_TIMEOUT = 1.0",
            "# SERVO_PERIOD = 1000000",
            "",
            "# [HAL]",
            "# HALFILE = machine.hal",
            "# POSTGUI_HALFILE = postgui_call_list.hal",
            "",
            "# [TRAJ]",
            "# COORDINATES = "
            + "".join(
                str(axis.get("id", "")).upper() for axis in hardware_payload.get("axes", [])
            ),
            "# LINEAR_UNITS = mm",
            "# ANGULAR_UNITS = degree",
            "# DEFAULT_VELOCITY = 10.0",
            "# MAX_VELOCITY = 50.0",
            "# MAX_ACCELERATION = 500.0",
            "",
        ]
    )

    for axis in hardware_payload.get("axes", []):
        letter = str(axis.get("id", "")).upper()
        if not letter:
            continue
        joint_numbers = ", ".join(str(n) for n in axis.get("joint_numbers", []))
        lines.extend(
            [
                f"# [AXIS_{letter}]",
                f"# JOINTS = {joint_numbers or '<joint numbers>'}",
                "# MAX_VELOCITY = <value>",
                "# MAX_ACCELERATION = <value>",
                "# MIN_LIMIT = <value>",
                "# MAX_LIMIT = <value>",
                "",
            ]
        )

    for joint in hardware_payload.get("joints", []):
        index = joint.get("joint_number", "?")
        joint_id = joint.get("id", "<joint id>")
        lines.extend(
            [
                f"# [JOINT_{index}]",
                f"# NAME = {joint_id}",
                "# TYPE = LINEAR",
                "# STEP_SCALE = <steps per unit>",
                "# MAX_VELOCITY = <value>",
                "# MAX_ACCELERATION = <value>",
                "# HOME = <position>",
                "# HOME_SEQUENCE = <order>",
                "",
            ]
        )

    lines.append("")
    return "\n".join(lines)


__all__ = ["render_ini_template"]
