"""``machine.ini`` renderer.

Unlike the earlier, fully-commented skeleton, this renders a
**live** INI: every section LinuxCNC needs to actually load a
configuration is populated with either a known-good default (lifted
from a real, working PrintNC machine — see
``machine_config/example/PrintNC-WEBGUI``) or a value derived from
the source profile's ``.cfg`` limits via :class:`AxisBuilder`. The
goal is "it compiles and LinuxCNC can start it" — not "it's a fully
tuned, ready-to-cut machine". Kinematics are assumed ``trivkins``
(see :mod:`.generator`); an axis can still drive more than one joint
(e.g. a dual-motor gantry axis), which is why ``coordinates=`` can
repeat a letter (``XYYZ``) and ``[KINS] JOINTS`` counts joints, not
axis letters.
"""

from __future__ import annotations

from typing import List

from domain_file_services import paths

from models.machineconfig.linuxcnc_models import Axis

#: PrintNC-WEBGUI's known-good ``[DISPLAY]`` block (see
#: ``machine_config/example/PrintNC-WEBGUI/Machine.ini``) — every
#: value here is a sane default for a bench mill/router, not
#: machine-specific, so it's safe to carry into every generated INI
#: verbatim.
_DISPLAY_DEFAULTS = """\
[DISPLAY]
#DISPLAY = axis
DISPLAY = dummy
EDITOR = gedit
POSITION_OFFSET = RELATIVE
POSITION_FEEDBACK = ACTUAL
ARCDIVISION = 64
GRIDS = 10mm 20mm 50mm 100mm 1in 2in 5in 10in
MAX_FEED_OVERRIDE = 4
MIN_SPINDLE_OVERRIDE = 0.5
MAX_SPINDLE_OVERRIDE = 4
DEFAULT_LINEAR_VELOCITY = 50.00
MIN_LINEAR_VELOCITY = 0
MAX_LINEAR_VELOCITY = 100.00

PROGRAM_PREFIX = {program_prefix}
INCREMENTS = 5mm 1mm .5mm .1mm .05mm .01mm .005mm

DEFAULT_SPINDLE_SPEED = 6000
"""


def _fmt(value: float) -> str:
    """Format a float without noisy trailing precision (``100.0``, not
    ``100.00000001`` or a bare ``100``)."""
    text = f"{float(value):.4f}".rstrip("0").rstrip(".")
    return text if "." in text else f"{text}.0"


def _posix(path) -> str:
    return str(path).replace("\\", "/")


def _coordinates(axes: List[Axis]) -> str:
    """``trivkins coordinates=`` string — one letter per joint, so a
    dual-motor axis repeats its letter (e.g. ``XYYZ``)."""
    return "".join(axis.letter * max(len(axis.joints), 1) for axis in axes)


def _joint_count(axes: List[Axis]) -> int:
    return sum(max(len(axis.joints), 1) for axis in axes)


def _render_axis_section(axis: Axis) -> List[str]:
    return [
        f"[AXIS_{axis.letter}]",
        f"MAX_VELOCITY = {_fmt(axis.max_velocity)}",
        f"MAX_ACCELERATION = {_fmt(axis.max_acceleration)}",
        f"MIN_LIMIT = {_fmt(axis.min_limit)}",
        f"MAX_LIMIT = {_fmt(axis.max_limit)}",
        "",
    ]


def _render_joint_section(joint) -> List[str]:
    return [
        f"[JOINT_{joint.joint_number}]",
        f"TYPE = {joint.type}",
        f"HOME = {_fmt(joint.home_position)}",
        f"MIN_LIMIT = {_fmt(joint.min_limit)}",
        f"MAX_LIMIT = {_fmt(joint.max_limit)}",
        f"MAX_VELOCITY = {_fmt(joint.max_velocity)}",
        f"MAX_ACCELERATION = {_fmt(joint.max_acceleration)}",
        f"STEPGEN_MAXACCEL = {_fmt(joint.stepgen_maxaccel)}",
        f"SCALE = {_fmt(joint.scale)}",
        f"FERROR = {_fmt(joint.ferror)}",
        f"MIN_FERROR = {_fmt(joint.min_ferror)}",
        f"HOME_OFFSET = {_fmt(joint.home_offset)}",
        f"HOME_SEARCH_VEL = {_fmt(joint.home_search_vel)}",
        f"HOME_LATCH_VEL = {_fmt(joint.home_latch_vel)}",
        "HOME_USE_INDEX = NO",
        f"HOME_SEQUENCE = {int(joint.home_sequence)}",
        "",
    ]


def render_ini_template(machine_name: str, axes: List[Axis]) -> str:
    """Render a live, loadable ``machine.ini``.

    Args:
        machine_name: Machine name (the source ``.cfg`` file stem) —
            written into ``[EMC] MACHINE`` and used as the ``.cft``
            profile reference.
        axes: The axis/joint list from
            ``AxisBuilder(graph, policy=AxisMappingPolicy.SPLIT_INTO_MULTIPLE_JOINTS).build()``
            — one joint per declared stepper, so a multi-motor axis
            (dual-Y gantry) renders every joint.
    """
    joint_count = _joint_count(axes)
    coordinates = _coordinates(axes) or "X"

    # Trajectory-level velocity is bounded by the slowest axis — a
    # machine can't move faster along a combined path than its
    # slowest contributing axis allows.
    axis_velocities = [a.max_velocity for a in axes if a.max_velocity > 0]
    traj_max_velocity = min(axis_velocities) if axis_velocities else 40.0
    traj_default_velocity = min(traj_max_velocity, max(traj_max_velocity * 0.1, 1.0))

    lines: List[str] = [
        "# machine.ini - generated by the LinuxCNC_UI machine templates",
        f"# Machine: {machine_name}",
        "#",
        "# This INI is meant to load and run in LinuxCNC (trivkins), not to",
        "# be a fully tuned, ready-to-cut machine. HAL wiring in machine.hal",
        "# still needs the operator's own pin assignments.",
        "",
        "[EMC]",
        f"MACHINE = {machine_name}",
        "DEBUG = 0",
        "VERSION = 1.1",
        "",
        _DISPLAY_DEFAULTS.format(program_prefix=_posix(paths.NC_FILES_DIR) + "/").rstrip("\n"),
        "",
        "[KINS]",
        f"JOINTS = {joint_count}",
        f"KINEMATICS = trivkins coordinates={coordinates}",
        "",
        "[TASK]",
        "TASK = milltask",
        "CYCLE_TIME = 0.010",
        "",
        "[RS274NGC]",
        "PARAMETER_FILE = linuxcnc.var",
        f"USER_M_PATH = {_posix(paths.M_CODES_DIR)}",
        "",
        "[EMCMOT]",
        "EMCMOT = motmod",
        "COMM_TIMEOUT = 30.0",
        "BASE_PERIOD = 100000",
        "SERVO_PERIOD = 1000000",
        "",
        "[HAL]",
        "HALFILE = machine.hal",
        "HALFILE = custom.hal",
        "POSTGUI_HALFILE = postgui_call_list.hal",
        "HALUI = halui",
        "",
        "[TRAJ]",
        f"COORDINATES = {coordinates}",
        "LINEAR_UNITS = mm",
        "ANGULAR_UNITS = degree",
        f"DEFAULT_LINEAR_VELOCITY = {_fmt(traj_default_velocity)}",
        f"MAX_LINEAR_VELOCITY = {_fmt(traj_max_velocity)}",
        "",
        "[APPLICATIONS]",
        f"APP = {_posix(paths.PROJECT_ROOT / 'start_network.sh')}",
        "",
        "[EMCIO]",
        "EMCIO = io",
        "CYCLE_TIME = 0.100",
        "TOOL_TABLE = tool.tbl",
        "",
    ]

    for axis in axes:
        lines.extend(_render_axis_section(axis))
        for joint in axis.joints:
            lines.extend(_render_joint_section(joint))

    return "\n".join(lines).rstrip("\n") + "\n"


__all__ = ["render_ini_template"]
