"""Parse and render the Visual HAL editor's signal block inside a ``.hal`` file.

Stays deliberately dumb (mirrors ``hal_mapper.py``'s style): pure text
processing, no filesystem I/O of its own — callers read/write the file
via the existing :class:`domain_file_services.MachineFileService`.

Only the single-line ``net <name> <pin> [=> | <=] <pin> ...`` sugar form
is understood. Everything else in the file (``setp``, ``loadrt``,
``addf``, ``loadusr``, ``source``, comments, and the multi-statement
``newsig``/``linksp``/``linkps`` form) is treated as opaque text and
passed through untouched.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import List

from models.hal import HalFileSignalWrite

MARKER_BEGIN = "# BEGIN VISUAL HAL EDITOR SIGNALS"
MARKER_END = "# END VISUAL HAL EDITOR SIGNALS"

_WARNING_LINES = [
    "# ============================================================",
    "# AUTO-GENERATED BY THE VISUAL HAL EDITOR.",
    "# Everything between this line and the END marker below is",
    "# regenerated every time this file is saved from the Visual",
    "# HAL Editor UI — hand edits in this section WILL BE LOST.",
    "# Edit signals from the Visual HAL Editor instead.",
    "# ============================================================",
]

_ARROWS = {"=>", "<="}


@dataclass
class ParsedSignal:
    """One ``net`` declaration found in a ``.hal`` file."""

    name: str
    pin_tokens: List[str] = field(default_factory=list)


def parse_net_lines(text: str) -> List[ParsedSignal]:
    """Extract every ``net <name> <pin> ...`` declaration from ``text``.

    Comments (``#...``) are stripped before tokenizing. Arrow tokens
    (``=>``/``<=``) are dropped — direction is resolved by the caller
    against real pin metadata, not by arrow position.
    """
    signals: List[ParsedSignal] = []
    for raw_line in text.splitlines():
        line = raw_line.split("#", 1)[0].strip()
        if not line:
            continue
        tokens = line.split()
        if tokens[0] != "net" or len(tokens) < 3:
            continue
        name = tokens[1]
        pin_tokens = [tok for tok in tokens[2:] if tok not in _ARROWS]
        if pin_tokens:
            signals.append(ParsedSignal(name=name, pin_tokens=pin_tokens))
    return signals


def _render_signal_line(signal: HalFileSignalWrite) -> str:
    pins = [signal.source] if signal.source else []
    pins.extend(signal.targets)
    pins = [p for p in pins if p]
    if signal.source and signal.targets:
        return f"net {signal.name} {signal.source} => {' '.join(signal.targets)}"
    return f"net {signal.name} {' '.join(pins)}"


def render_signals_block(signals: List[HalFileSignalWrite]) -> str:
    """Render the full warning-commented, marker-wrapped signals section."""
    lines = list(_WARNING_LINES)
    lines.append(MARKER_BEGIN)
    for signal in signals:
        if not signal.name or (not signal.source and not signal.targets):
            continue
        lines.append(_render_signal_line(signal))
    lines.append(MARKER_END)
    return "\n".join(lines)


def apply_signals(existing_text: str, signals: List[HalFileSignalWrite]) -> str:
    """Insert/replace the delimited signals section inside ``existing_text``.

    Content outside the ``MARKER_BEGIN``/``MARKER_END`` pair is returned
    unchanged. When the markers aren't present yet, the block is appended
    at the end of the file (blank-line separated).
    """
    block = render_signals_block(signals)
    lines = existing_text.splitlines()

    begin_idx = next((i for i, l in enumerate(lines) if l.strip() == MARKER_BEGIN), None)
    end_idx = next((i for i, l in enumerate(lines) if l.strip() == MARKER_END), None)

    if begin_idx is not None and end_idx is not None and end_idx >= begin_idx:
        # The warning header precedes the BEGIN marker — replace back to
        # the start of that header block if it's there, else just the
        # marker span itself.
        header_start = begin_idx
        while header_start > 0 and lines[header_start - 1].strip() in _WARNING_LINES:
            header_start -= 1
        new_lines = lines[:header_start] + block.splitlines() + lines[end_idx + 1 :]
        result = "\n".join(new_lines)
    else:
        result = existing_text
        if result and not result.endswith("\n"):
            result += "\n"
        if result.strip():
            result += "\n"
        result += block

    if not result.endswith("\n"):
        result += "\n"
    return result


__all__ = [
    "MARKER_BEGIN",
    "MARKER_END",
    "ParsedSignal",
    "parse_net_lines",
    "render_signals_block",
    "apply_signals",
]
